/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type InvitationChangeRequest,
    InvitationChangeRequestFromJSON,
    InvitationChangeRequestToJSON,
} from '../models/InvitationChangeRequest';
import {
    type InvitationPage,
    InvitationPageFromJSON,
    InvitationPageToJSON,
} from '../models/InvitationPage';
import {
    type MemberList,
    MemberListFromJSON,
    MemberListToJSON,
} from '../models/MemberList';
import {
    type MemberProfile,
    MemberProfileFromJSON,
    MemberProfileToJSON,
} from '../models/MemberProfile';
import {
    type ProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/ProblemDetails';
import {
    type ProvisionMemberRequest,
    ProvisionMemberRequestFromJSON,
    ProvisionMemberRequestToJSON,
} from '../models/ProvisionMemberRequest';
import {
    type SetManagerRequest,
    SetManagerRequestFromJSON,
    SetManagerRequestToJSON,
} from '../models/SetManagerRequest';
import {
    type UpdateMemberRequest,
    UpdateMemberRequestFromJSON,
    UpdateMemberRequestToJSON,
} from '../models/UpdateMemberRequest';

export interface AssignManagerRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    setManagerRequest: SetManagerRequest;
}

export interface CancelInvitationRequest {
    /**
     *
     */
    memberId: string;
    /**
     *
     */
    invitationChangeRequest: InvitationChangeRequest;
}

export interface CheckManagementAccessRequest {
    /**
     *
     */
    memberId: string;
}

export interface GetMemberRequest {
    /**
     *
     */
    memberId: string;
}

export interface ListInvitationsRequest {
    /**
     *
     */
    after?: string;
    /**
     *
     */
    limit?: number;
}

export interface ProvisionMemberOperationRequest {
    /**
     *
     */
    provisionMemberRequest: ProvisionMemberRequest;
}

export interface ResendInvitationRequest {
    /**
     *
     */
    memberId: string;
    /**
     *
     */
    invitationChangeRequest: InvitationChangeRequest;
}

export interface UpdateMemberOperationRequest {
    /**
     *
     */
    memberId: string;
    /**
     *
     */
    updateMemberRequest: UpdateMemberRequest;
}

/**
 *
 */
export class AccessApi extends runtime.BaseAPI {

    /**
     * Creates request options for assignManager without sending the request
     */
    async assignManagerRequestOpts(requestParameters: AssignManagerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling assignManager().'
            );
        }

        if (requestParameters['setManagerRequest'] == null) {
            throw new runtime.RequiredError(
                'setManagerRequest',
                'Required parameter "setManagerRequest" was null or undefined when calling assignManager().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/admin/members/{employeeId}/manager`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetManagerRequestToJSON(requestParameters['setManagerRequest']),
        };
    }

    /**
     */
    async assignManagerRaw(requestParameters: AssignManagerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.assignManagerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async assignManager(requestParameters: AssignManagerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.assignManagerRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for cancelInvitation without sending the request
     */
    async cancelInvitationRequestOpts(requestParameters: CancelInvitationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling cancelInvitation().'
            );
        }

        if (requestParameters['invitationChangeRequest'] == null) {
            throw new runtime.RequiredError(
                'invitationChangeRequest',
                'Required parameter "invitationChangeRequest" was null or undefined when calling cancelInvitation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/admin/members/{memberId}/invitation/cancel`;
        urlPath = urlPath.replace('{memberId}', encodeURIComponent(String(requestParameters['memberId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InvitationChangeRequestToJSON(requestParameters['invitationChangeRequest']),
        };
    }

    /**
     */
    async cancelInvitationRaw(requestParameters: CancelInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.cancelInvitationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async cancelInvitation(requestParameters: CancelInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cancelInvitationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for checkManagementAccess without sending the request
     */
    async checkManagementAccessRequestOpts(requestParameters: CheckManagementAccessRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling checkManagementAccess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/members/{memberId}/management-access`;
        urlPath = urlPath.replace('{memberId}', encodeURIComponent(String(requestParameters['memberId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read-only relationship/role guard. Does not create or approve any request.
     */
    async checkManagementAccessRaw(requestParameters: CheckManagementAccessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemberProfile>> {
        const requestOptions = await this.checkManagementAccessRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MemberProfileFromJSON(jsonValue));
    }

    /**
     * Read-only relationship/role guard. Does not create or approve any request.
     */
    async checkManagementAccess(requestParameters: CheckManagementAccessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemberProfile> {
        const response = await this.checkManagementAccessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCurrentMember without sending the request
     */
    async getCurrentMemberRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCurrentMemberRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemberProfile>> {
        const requestOptions = await this.getCurrentMemberRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MemberProfileFromJSON(jsonValue));
    }

    /**
     */
    async getCurrentMember(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemberProfile> {
        const response = await this.getCurrentMemberRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMember without sending the request
     */
    async getMemberRequestOpts(requestParameters: GetMemberRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling getMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/members/{memberId}`;
        urlPath = urlPath.replace('{memberId}', encodeURIComponent(String(requestParameters['memberId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getMemberRaw(requestParameters: GetMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemberProfile>> {
        const requestOptions = await this.getMemberRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MemberProfileFromJSON(jsonValue));
    }

    /**
     */
    async getMember(requestParameters: GetMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemberProfile> {
        const response = await this.getMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listInvitations without sending the request
     */
    async listInvitationsRequestOpts(requestParameters: ListInvitationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['after'] != null) {
            queryParameters['after'] = requestParameters['after'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/admin/invitations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listInvitationsRaw(requestParameters: ListInvitationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvitationPage>> {
        const requestOptions = await this.listInvitationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvitationPageFromJSON(jsonValue));
    }

    /**
     */
    async listInvitations(requestParameters: ListInvitationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvitationPage> {
        const response = await this.listInvitationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMembers without sending the request
     */
    async listMembersRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/members`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listMembersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemberList>> {
        const requestOptions = await this.listMembersRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MemberListFromJSON(jsonValue));
    }

    /**
     */
    async listMembers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemberList> {
        const response = await this.listMembersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for provisionMember without sending the request
     */
    async provisionMemberRequestOpts(requestParameters: ProvisionMemberOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['provisionMemberRequest'] == null) {
            throw new runtime.RequiredError(
                'provisionMemberRequest',
                'Required parameter "provisionMemberRequest" was null or undefined when calling provisionMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/admin/members`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProvisionMemberRequestToJSON(requestParameters['provisionMemberRequest']),
        };
    }

    /**
     * Create an admitted member and durable invitation. Repeating the identical normalized request by the same administrator returns success without creating or resending.
     */
    async provisionMemberRaw(requestParameters: ProvisionMemberOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.provisionMemberRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create an admitted member and durable invitation. Repeating the identical normalized request by the same administrator returns success without creating or resending.
     */
    async provisionMember(requestParameters: ProvisionMemberOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.provisionMemberRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for resendInvitation without sending the request
     */
    async resendInvitationRequestOpts(requestParameters: ResendInvitationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling resendInvitation().'
            );
        }

        if (requestParameters['invitationChangeRequest'] == null) {
            throw new runtime.RequiredError(
                'invitationChangeRequest',
                'Required parameter "invitationChangeRequest" was null or undefined when calling resendInvitation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/admin/members/{memberId}/invitation/resend`;
        urlPath = urlPath.replace('{memberId}', encodeURIComponent(String(requestParameters['memberId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InvitationChangeRequestToJSON(requestParameters['invitationChangeRequest']),
        };
    }

    /**
     */
    async resendInvitationRaw(requestParameters: ResendInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.resendInvitationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async resendInvitation(requestParameters: ResendInvitationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.resendInvitationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateMember without sending the request
     */
    async updateMemberRequestOpts(requestParameters: UpdateMemberOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling updateMember().'
            );
        }

        if (requestParameters['updateMemberRequest'] == null) {
            throw new runtime.RequiredError(
                'updateMemberRequest',
                'Required parameter "updateMemberRequest" was null or undefined when calling updateMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/admin/members/{memberId}`;
        urlPath = urlPath.replace('{memberId}', encodeURIComponent(String(requestParameters['memberId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMemberRequestToJSON(requestParameters['updateMemberRequest']),
        };
    }

    /**
     */
    async updateMemberRaw(requestParameters: UpdateMemberOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateMemberRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateMember(requestParameters: UpdateMemberOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateMemberRaw(requestParameters, initOverrides);
    }

}
