/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AccessTokenResponse,
    AccessTokenResponseFromJSON,
    AccessTokenResponseToJSON,
} from '../models/AccessTokenResponse';
import {
    type CompleteAccountRequest,
    CompleteAccountRequestFromJSON,
    CompleteAccountRequestToJSON,
} from '../models/CompleteAccountRequest';
import {
    type Credentials,
    CredentialsFromJSON,
    CredentialsToJSON,
} from '../models/Credentials';
import {
    type CsrfToken,
    CsrfTokenFromJSON,
    CsrfTokenToJSON,
} from '../models/CsrfToken';
import {
    type EmailRequest,
    EmailRequestFromJSON,
    EmailRequestToJSON,
} from '../models/EmailRequest';
import {
    type ProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/ProblemDetails';
import {
    type RefreshRequest,
    RefreshRequestFromJSON,
    RefreshRequestToJSON,
} from '../models/RefreshRequest';

export interface ActivateAccountRequest {
    /**
     *
     */
    completeAccountRequest: CompleteAccountRequest;
}

export interface LoginTokenRequest {
    /**
     *
     */
    credentials: Credentials;
}

export interface LoginWebRequest {
    /**
     *
     */
    credentials: Credentials;
}

export interface RefreshSessionRequest {
    /**
     *
     */
    refreshRequest: RefreshRequest;
}

export interface RequestActivationRequest {
    /**
     *
     */
    emailRequest: EmailRequest;
}

export interface RequestRecoveryRequest {
    /**
     *
     */
    emailRequest: EmailRequest;
}

export interface ResetPasswordRequest {
    /**
     *
     */
    completeAccountRequest: CompleteAccountRequest;
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Creates request options for activateAccount without sending the request
     */
    async activateAccountRequestOpts(requestParameters: ActivateAccountRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['completeAccountRequest'] == null) {
            throw new runtime.RequiredError(
                'completeAccountRequest',
                'Required parameter "completeAccountRequest" was null or undefined when calling activateAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/activation/complete`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CompleteAccountRequestToJSON(requestParameters['completeAccountRequest']),
        };
    }

    /**
     */
    async activateAccountRaw(requestParameters: ActivateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.activateAccountRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async activateAccount(requestParameters: ActivateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.activateAccountRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getCsrfToken without sending the request
     */
    async getCsrfTokenRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/auth/csrf`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCsrfTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CsrfToken>> {
        const requestOptions = await this.getCsrfTokenRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CsrfTokenFromJSON(jsonValue));
    }

    /**
     */
    async getCsrfToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CsrfToken> {
        const response = await this.getCsrfTokenRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for loginToken without sending the request
     */
    async loginTokenRequestOpts(requestParameters: LoginTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['credentials'] == null) {
            throw new runtime.RequiredError(
                'credentials',
                'Required parameter "credentials" was null or undefined when calling loginToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/token/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CredentialsToJSON(requestParameters['credentials']),
        };
    }

    /**
     */
    async loginTokenRaw(requestParameters: LoginTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccessTokenResponse>> {
        const requestOptions = await this.loginTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccessTokenResponseFromJSON(jsonValue));
    }

    /**
     */
    async loginToken(requestParameters: LoginTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccessTokenResponse> {
        const response = await this.loginTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for loginWeb without sending the request
     */
    async loginWebRequestOpts(requestParameters: LoginWebRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['credentials'] == null) {
            throw new runtime.RequiredError(
                'credentials',
                'Required parameter "credentials" was null or undefined when calling loginWeb().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/web/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CredentialsToJSON(requestParameters['credentials']),
        };
    }

    /**
     */
    async loginWebRaw(requestParameters: LoginWebRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.loginWebRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async loginWeb(requestParameters: LoginWebRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.loginWebRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for logout without sending the request
     */
    async logoutRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/auth/logout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.logoutRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.logoutRaw(initOverrides);
    }

    /**
     * Creates request options for refreshSession without sending the request
     */
    async refreshSessionRequestOpts(requestParameters: RefreshSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['refreshRequest'] == null) {
            throw new runtime.RequiredError(
                'refreshRequest',
                'Required parameter "refreshRequest" was null or undefined when calling refreshSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/token/refresh`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RefreshRequestToJSON(requestParameters['refreshRequest']),
        };
    }

    /**
     */
    async refreshSessionRaw(requestParameters: RefreshSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccessTokenResponse>> {
        const requestOptions = await this.refreshSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccessTokenResponseFromJSON(jsonValue));
    }

    /**
     */
    async refreshSession(requestParameters: RefreshSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccessTokenResponse> {
        const response = await this.refreshSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for requestActivation without sending the request
     */
    async requestActivationRequestOpts(requestParameters: RequestActivationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['emailRequest'] == null) {
            throw new runtime.RequiredError(
                'emailRequest',
                'Required parameter "emailRequest" was null or undefined when calling requestActivation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/activation/request`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmailRequestToJSON(requestParameters['emailRequest']),
        };
    }

    /**
     */
    async requestActivationRaw(requestParameters: RequestActivationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.requestActivationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async requestActivation(requestParameters: RequestActivationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.requestActivationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for requestRecovery without sending the request
     */
    async requestRecoveryRequestOpts(requestParameters: RequestRecoveryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['emailRequest'] == null) {
            throw new runtime.RequiredError(
                'emailRequest',
                'Required parameter "emailRequest" was null or undefined when calling requestRecovery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/recovery/request`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmailRequestToJSON(requestParameters['emailRequest']),
        };
    }

    /**
     */
    async requestRecoveryRaw(requestParameters: RequestRecoveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.requestRecoveryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async requestRecovery(requestParameters: RequestRecoveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.requestRecoveryRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for resetPassword without sending the request
     */
    async resetPasswordRequestOpts(requestParameters: ResetPasswordRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['completeAccountRequest'] == null) {
            throw new runtime.RequiredError(
                'completeAccountRequest',
                'Required parameter "completeAccountRequest" was null or undefined when calling resetPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/recovery/complete`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CompleteAccountRequestToJSON(requestParameters['completeAccountRequest']),
        };
    }

    /**
     */
    async resetPasswordRaw(requestParameters: ResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.resetPasswordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async resetPassword(requestParameters: ResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.resetPasswordRaw(requestParameters, initOverrides);
    }

}
