/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DeviceReceiptInput,
    DeviceReceiptInputFromJSON,
    DeviceReceiptInputToJSON,
} from '../models/DeviceReceiptInput';
import {
    type DeviceRegistrationInput,
    DeviceRegistrationInputFromJSON,
    DeviceRegistrationInputToJSON,
} from '../models/DeviceRegistrationInput';
import {
    type DeviceRegistrationView,
    DeviceRegistrationViewFromJSON,
    DeviceRegistrationViewToJSON,
} from '../models/DeviceRegistrationView';
import {
    type NotificationCapabilities,
    NotificationCapabilitiesFromJSON,
    NotificationCapabilitiesToJSON,
} from '../models/NotificationCapabilities';
import {
    type NotificationCount,
    NotificationCountFromJSON,
    NotificationCountToJSON,
} from '../models/NotificationCount';
import {
    type NotificationOperations,
    NotificationOperationsFromJSON,
    NotificationOperationsToJSON,
} from '../models/NotificationOperations';
import {
    type NotificationPage,
    NotificationPageFromJSON,
    NotificationPageToJSON,
} from '../models/NotificationPage';
import {
    type NotificationReadInput,
    NotificationReadInputFromJSON,
    NotificationReadInputToJSON,
} from '../models/NotificationReadInput';
import {
    type NotificationView,
    NotificationViewFromJSON,
    NotificationViewToJSON,
} from '../models/NotificationView';
import {
    type ProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/ProblemDetails';
import {
    type RetryNotificationInput,
    RetryNotificationInputFromJSON,
    RetryNotificationInputToJSON,
} from '../models/RetryNotificationInput';

export interface GetNotificationRequest {
    /**
     *
     */
    notificationId: string;
}

export interface ListNotificationsRequest {
    /**
     *
     */
    offset?: number;
    /**
     *
     */
    limit?: number;
    /**
     *
     */
    unreadOnly?: boolean;
    /**
     *
     */
    historical?: boolean;
}

export interface RegisterPushDeviceRequest {
    /**
     *
     */
    deviceRegistrationInput: DeviceRegistrationInput;
}

export interface RemovePushDeviceRequest {
    /**
     *
     */
    installationId: string;
}

export interface ReportNotificationDeviceReceiptRequest {
    /**
     *
     */
    notificationId: string;
    /**
     *
     */
    deviceReceiptInput: DeviceReceiptInput;
}

export interface RetryFailedNotificationWorkRequest {
    /**
     *
     */
    retryNotificationInput: RetryNotificationInput;
}

export interface SetNotificationReadRequest {
    /**
     *
     */
    notificationId: string;
    /**
     *
     */
    notificationReadInput: NotificationReadInput;
}

/**
 *
 */
export class NotificationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getNotification without sending the request
     */
    async getNotificationRequestOpts(requestParameters: GetNotificationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['notificationId'] == null) {
            throw new runtime.RequiredError(
                'notificationId',
                'Required parameter "notificationId" was null or undefined when calling getNotification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/notifications/{notificationId}`;
        urlPath = urlPath.replace('{notificationId}', encodeURIComponent(String(requestParameters['notificationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getNotificationRaw(requestParameters: GetNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationView>> {
        const requestOptions = await this.getNotificationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationViewFromJSON(jsonValue));
    }

    /**
     */
    async getNotification(requestParameters: GetNotificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationView> {
        const response = await this.getNotificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNotificationCapabilities without sending the request
     */
    async getNotificationCapabilitiesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/notifications/capabilities`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getNotificationCapabilitiesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationCapabilities>> {
        const requestOptions = await this.getNotificationCapabilitiesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationCapabilitiesFromJSON(jsonValue));
    }

    /**
     */
    async getNotificationCapabilities(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationCapabilities> {
        const response = await this.getNotificationCapabilitiesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNotificationOperations without sending the request
     */
    async getNotificationOperationsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/notifications/operations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getNotificationOperationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationOperations>> {
        const requestOptions = await this.getNotificationOperationsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationOperationsFromJSON(jsonValue));
    }

    /**
     */
    async getNotificationOperations(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationOperations> {
        const response = await this.getNotificationOperationsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNotificationUnreadCount without sending the request
     */
    async getNotificationUnreadCountRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/notifications/unread-count`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getNotificationUnreadCountRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationCount>> {
        const requestOptions = await this.getNotificationUnreadCountRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationCountFromJSON(jsonValue));
    }

    /**
     */
    async getNotificationUnreadCount(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationCount> {
        const response = await this.getNotificationUnreadCountRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listNotifications without sending the request
     */
    async listNotificationsRequestOpts(requestParameters: ListNotificationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['unreadOnly'] != null) {
            queryParameters['unreadOnly'] = requestParameters['unreadOnly'];
        }

        if (requestParameters['historical'] != null) {
            queryParameters['historical'] = requestParameters['historical'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/notifications`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listNotificationsRaw(requestParameters: ListNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationPage>> {
        const requestOptions = await this.listNotificationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationPageFromJSON(jsonValue));
    }

    /**
     */
    async listNotifications(requestParameters: ListNotificationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationPage> {
        const response = await this.listNotificationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerPushDevice without sending the request
     */
    async registerPushDeviceRequestOpts(requestParameters: RegisterPushDeviceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deviceRegistrationInput'] == null) {
            throw new runtime.RequiredError(
                'deviceRegistrationInput',
                'Required parameter "deviceRegistrationInput" was null or undefined when calling registerPushDevice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/notifications/devices`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DeviceRegistrationInputToJSON(requestParameters['deviceRegistrationInput']),
        };
    }

    /**
     */
    async registerPushDeviceRaw(requestParameters: RegisterPushDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeviceRegistrationView>> {
        const requestOptions = await this.registerPushDeviceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeviceRegistrationViewFromJSON(jsonValue));
    }

    /**
     */
    async registerPushDevice(requestParameters: RegisterPushDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeviceRegistrationView> {
        const response = await this.registerPushDeviceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removePushDevice without sending the request
     */
    async removePushDeviceRequestOpts(requestParameters: RemovePushDeviceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['installationId'] == null) {
            throw new runtime.RequiredError(
                'installationId',
                'Required parameter "installationId" was null or undefined when calling removePushDevice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/notifications/devices/{installationId}`;
        urlPath = urlPath.replace('{installationId}', encodeURIComponent(String(requestParameters['installationId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async removePushDeviceRaw(requestParameters: RemovePushDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.removePushDeviceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async removePushDevice(requestParameters: RemovePushDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removePushDeviceRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for reportNotificationDeviceReceipt without sending the request
     */
    async reportNotificationDeviceReceiptRequestOpts(requestParameters: ReportNotificationDeviceReceiptRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['notificationId'] == null) {
            throw new runtime.RequiredError(
                'notificationId',
                'Required parameter "notificationId" was null or undefined when calling reportNotificationDeviceReceipt().'
            );
        }

        if (requestParameters['deviceReceiptInput'] == null) {
            throw new runtime.RequiredError(
                'deviceReceiptInput',
                'Required parameter "deviceReceiptInput" was null or undefined when calling reportNotificationDeviceReceipt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/notifications/{notificationId}/device-receipt`;
        urlPath = urlPath.replace('{notificationId}', encodeURIComponent(String(requestParameters['notificationId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DeviceReceiptInputToJSON(requestParameters['deviceReceiptInput']),
        };
    }

    /**
     */
    async reportNotificationDeviceReceiptRaw(requestParameters: ReportNotificationDeviceReceiptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.reportNotificationDeviceReceiptRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async reportNotificationDeviceReceipt(requestParameters: ReportNotificationDeviceReceiptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.reportNotificationDeviceReceiptRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for retryFailedNotificationWork without sending the request
     */
    async retryFailedNotificationWorkRequestOpts(requestParameters: RetryFailedNotificationWorkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['retryNotificationInput'] == null) {
            throw new runtime.RequiredError(
                'retryNotificationInput',
                'Required parameter "retryNotificationInput" was null or undefined when calling retryFailedNotificationWork().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/notifications/operations/retry`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RetryNotificationInputToJSON(requestParameters['retryNotificationInput']),
        };
    }

    /**
     */
    async retryFailedNotificationWorkRaw(requestParameters: RetryFailedNotificationWorkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.retryFailedNotificationWorkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async retryFailedNotificationWork(requestParameters: RetryFailedNotificationWorkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.retryFailedNotificationWorkRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for setNotificationRead without sending the request
     */
    async setNotificationReadRequestOpts(requestParameters: SetNotificationReadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['notificationId'] == null) {
            throw new runtime.RequiredError(
                'notificationId',
                'Required parameter "notificationId" was null or undefined when calling setNotificationRead().'
            );
        }

        if (requestParameters['notificationReadInput'] == null) {
            throw new runtime.RequiredError(
                'notificationReadInput',
                'Required parameter "notificationReadInput" was null or undefined when calling setNotificationRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/notifications/{notificationId}/read`;
        urlPath = urlPath.replace('{notificationId}', encodeURIComponent(String(requestParameters['notificationId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NotificationReadInputToJSON(requestParameters['notificationReadInput']),
        };
    }

    /**
     */
    async setNotificationReadRaw(requestParameters: SetNotificationReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationView>> {
        const requestOptions = await this.setNotificationReadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationViewFromJSON(jsonValue));
    }

    /**
     */
    async setNotificationRead(requestParameters: SetNotificationReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationView> {
        const response = await this.setNotificationReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
