/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AcceptProposalInput,
    AcceptProposalInputFromJSON,
    AcceptProposalInputToJSON,
} from '../models/AcceptProposalInput';
import {
    type AssignedTaskState,
    AssignedTaskStateFromJSON,
    AssignedTaskStateToJSON,
} from '../models/AssignedTaskState';
import {
    type CalendarView,
    CalendarViewFromJSON,
    CalendarViewToJSON,
} from '../models/CalendarView';
import {
    type CommentInput,
    CommentInputFromJSON,
    CommentInputToJSON,
} from '../models/CommentInput';
import {
    type CommentPage,
    CommentPageFromJSON,
    CommentPageToJSON,
} from '../models/CommentPage';
import {
    type DatePreview,
    DatePreviewFromJSON,
    DatePreviewToJSON,
} from '../models/DatePreview';
import {
    type DecisionInput,
    DecisionInputFromJSON,
    DecisionInputToJSON,
} from '../models/DecisionInput';
import {
    type DraftInput,
    DraftInputFromJSON,
    DraftInputToJSON,
} from '../models/DraftInput';
import {
    type MutationReceipt,
    MutationReceiptFromJSON,
    MutationReceiptToJSON,
} from '../models/MutationReceipt';
import {
    type OnsiteAcknowledgeInput,
    OnsiteAcknowledgeInputFromJSON,
    OnsiteAcknowledgeInputToJSON,
} from '../models/OnsiteAcknowledgeInput';
import {
    type OnsiteInput,
    OnsiteInputFromJSON,
    OnsiteInputToJSON,
} from '../models/OnsiteInput';
import {
    type OnsitePage,
    OnsitePageFromJSON,
    OnsitePageToJSON,
} from '../models/OnsitePage';
import {
    type OnsitePreview,
    OnsitePreviewFromJSON,
    OnsitePreviewToJSON,
} from '../models/OnsitePreview';
import {
    type OnsiteState,
    OnsiteStateFromJSON,
    OnsiteStateToJSON,
} from '../models/OnsiteState';
import {
    type OnsiteView,
    OnsiteViewFromJSON,
    OnsiteViewToJSON,
} from '../models/OnsiteView';
import {
    type PatternInput,
    PatternInputFromJSON,
    PatternInputToJSON,
} from '../models/PatternInput';
import {
    type PatternPage,
    PatternPageFromJSON,
    PatternPageToJSON,
} from '../models/PatternPage';
import {
    type ProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/ProblemDetails';
import {
    type ProposalInput,
    ProposalInputFromJSON,
    ProposalInputToJSON,
} from '../models/ProposalInput';
import {
    type ProposalPage,
    ProposalPageFromJSON,
    ProposalPageToJSON,
} from '../models/ProposalPage';
import {
    type RequestPage,
    RequestPageFromJSON,
    RequestPageToJSON,
} from '../models/RequestPage';
import {
    type RequestState,
    RequestStateFromJSON,
    RequestStateToJSON,
} from '../models/RequestState';
import {
    type RequestView,
    RequestViewFromJSON,
    RequestViewToJSON,
} from '../models/RequestView';
import {
    type SubmitInput,
    SubmitInputFromJSON,
    SubmitInputToJSON,
} from '../models/SubmitInput';
import {
    type TaskInput,
    TaskInputFromJSON,
    TaskInputToJSON,
} from '../models/TaskInput';
import {
    type TaskPage,
    TaskPageFromJSON,
    TaskPageToJSON,
} from '../models/TaskPage';
import {
    type TaskProgressInput,
    TaskProgressInputFromJSON,
    TaskProgressInputToJSON,
} from '../models/TaskProgressInput';
import {
    type TaskView,
    TaskViewFromJSON,
    TaskViewToJSON,
} from '../models/TaskView';
import {
    type WithdrawInput,
    WithdrawInputFromJSON,
    WithdrawInputToJSON,
} from '../models/WithdrawInput';
import {
    type WorkCommentInput,
    WorkCommentInputFromJSON,
    WorkCommentInputToJSON,
} from '../models/WorkCommentInput';
import {
    type WorkContext,
    WorkContextFromJSON,
    WorkContextToJSON,
} from '../models/WorkContext';
import {
    type WorkEntryPage,
    WorkEntryPageFromJSON,
    WorkEntryPageToJSON,
} from '../models/WorkEntryPage';
import {
    type WorkVersionInput,
    WorkVersionInputFromJSON,
    WorkVersionInputToJSON,
} from '../models/WorkVersionInput';

export interface AcceptCounterproposalRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    proposalId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    acceptProposalInput: AcceptProposalInput;
}

export interface AcknowledgeOnsiteRequirementRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    requirementId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    onsiteAcknowledgeInput: OnsiteAcknowledgeInput;
}

export interface AddPlanningCommentRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    requestId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    commentInput: CommentInput;
}

export interface AddWorkCommentRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    kind: WorkContext;
    /**
     *
     */
    contextId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    workCommentInput: WorkCommentInput;
}

export interface CancelOnsiteRequirementRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    requirementId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    workVersionInput: WorkVersionInput;
}

export interface CreateAssignedTaskRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    taskInput: TaskInput;
}

export interface CreateCounterproposalRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    requestId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    proposalInput: ProposalInput;
}

export interface CreateOnsiteRequirementRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    onsiteInput: OnsiteInput;
}

export interface CreatePlanningDraftRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    draftInput: DraftInput;
}

export interface DecidePlanningDaysRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    requestId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    decisionInput: DecisionInput;
}

export interface EditAssignedTaskRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    taskId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    taskInput: TaskInput;
}

export interface EditOnsiteRequirementRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    requirementId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    onsiteInput: OnsiteInput;
}

export interface EditPlanningDraftRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    requestId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    draftInput: DraftInput;
}

export interface GetAssignedTaskRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    taskId: string;
}

export interface GetCalendarRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    from: Date;
    /**
     *
     */
    to: Date;
}

export interface GetOnsiteRequirementRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    requirementId: string;
}

export interface GetPlanningRequestRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    requestId: string;
}

export interface ListAssignedTasksRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    offset?: number;
    /**
     *
     */
    limit?: number;
    /**
     *
     */
    state?: AssignedTaskState;
}

export interface ListCounterproposalsRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    requestId: string;
    /**
     *
     */
    offset?: number;
    /**
     *
     */
    limit?: number;
}

export interface ListOnsiteRequirementsRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    offset?: number;
    /**
     *
     */
    limit?: number;
    /**
     *
     */
    state?: OnsiteState;
}

export interface ListPlanningCommentsRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    requestId: string;
    /**
     *
     */
    offset?: number;
    /**
     *
     */
    limit?: number;
}

export interface ListPlanningRequestsRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    offset?: number;
    /**
     *
     */
    limit?: number;
    /**
     *
     */
    state?: RequestState;
}

export interface ListWeeklyPatternsRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    offset?: number;
    /**
     *
     */
    limit?: number;
}

export interface ListWorkEntriesRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    kind: WorkContext;
    /**
     *
     */
    contextId: string;
    /**
     *
     */
    offset?: number;
    /**
     *
     */
    limit?: number;
}

export interface PreviewOnsiteRequirementRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    from: Date;
    /**
     *
     */
    to: Date;
    /**
     *
     */
    location: string;
    /**
     *
     */
    excludes?: string;
}

export interface PreviewPlanningDatesRequest {
    /**
     *
     */
    from: Date;
    /**
     *
     */
    to: Date;
    /**
     *
     */
    includeWeekends?: boolean;
}

export interface ReviseCounterproposalRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    requestId: string;
    /**
     *
     */
    proposalId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    proposalInput: ProposalInput;
}

export interface SetWeeklyPatternRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    patternInput: PatternInput;
}

export interface SubmitPlanningRequestRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    requestId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    submitInput: SubmitInput;
}

export interface UpdateTaskProgressRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    taskId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    taskProgressInput: TaskProgressInput;
}

export interface WithdrawPlanningDaysRequest {
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    requestId: string;
    /**
     *
     */
    idempotencyKey: string;
    /**
     *
     */
    withdrawInput: WithdrawInput;
}

/**
 *
 */
export class PlanningApi extends runtime.BaseAPI {

    /**
     * Creates request options for acceptCounterproposal without sending the request
     */
    async acceptCounterproposalRequestOpts(requestParameters: AcceptCounterproposalRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling acceptCounterproposal().'
            );
        }

        if (requestParameters['proposalId'] == null) {
            throw new runtime.RequiredError(
                'proposalId',
                'Required parameter "proposalId" was null or undefined when calling acceptCounterproposal().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling acceptCounterproposal().'
            );
        }

        if (requestParameters['acceptProposalInput'] == null) {
            throw new runtime.RequiredError(
                'acceptProposalInput',
                'Required parameter "acceptProposalInput" was null or undefined when calling acceptCounterproposal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/proposals/{proposalId}/accept`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{proposalId}', encodeURIComponent(String(requestParameters['proposalId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AcceptProposalInputToJSON(requestParameters['acceptProposalInput']),
        };
    }

    /**
     */
    async acceptCounterproposalRaw(requestParameters: AcceptCounterproposalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.acceptCounterproposalRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async acceptCounterproposal(requestParameters: AcceptCounterproposalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.acceptCounterproposalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for acknowledgeOnsiteRequirement without sending the request
     */
    async acknowledgeOnsiteRequirementRequestOpts(requestParameters: AcknowledgeOnsiteRequirementRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling acknowledgeOnsiteRequirement().'
            );
        }

        if (requestParameters['requirementId'] == null) {
            throw new runtime.RequiredError(
                'requirementId',
                'Required parameter "requirementId" was null or undefined when calling acknowledgeOnsiteRequirement().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling acknowledgeOnsiteRequirement().'
            );
        }

        if (requestParameters['onsiteAcknowledgeInput'] == null) {
            throw new runtime.RequiredError(
                'onsiteAcknowledgeInput',
                'Required parameter "onsiteAcknowledgeInput" was null or undefined when calling acknowledgeOnsiteRequirement().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/requirements/{requirementId}/acknowledge`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{requirementId}', encodeURIComponent(String(requestParameters['requirementId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OnsiteAcknowledgeInputToJSON(requestParameters['onsiteAcknowledgeInput']),
        };
    }

    /**
     */
    async acknowledgeOnsiteRequirementRaw(requestParameters: AcknowledgeOnsiteRequirementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.acknowledgeOnsiteRequirementRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async acknowledgeOnsiteRequirement(requestParameters: AcknowledgeOnsiteRequirementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.acknowledgeOnsiteRequirementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for addPlanningComment without sending the request
     */
    async addPlanningCommentRequestOpts(requestParameters: AddPlanningCommentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling addPlanningComment().'
            );
        }

        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling addPlanningComment().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling addPlanningComment().'
            );
        }

        if (requestParameters['commentInput'] == null) {
            throw new runtime.RequiredError(
                'commentInput',
                'Required parameter "commentInput" was null or undefined when calling addPlanningComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/requests/{requestId}/comments`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{requestId}', encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CommentInputToJSON(requestParameters['commentInput']),
        };
    }

    /**
     */
    async addPlanningCommentRaw(requestParameters: AddPlanningCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.addPlanningCommentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async addPlanningComment(requestParameters: AddPlanningCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.addPlanningCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for addWorkComment without sending the request
     */
    async addWorkCommentRequestOpts(requestParameters: AddWorkCommentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling addWorkComment().'
            );
        }

        if (requestParameters['kind'] == null) {
            throw new runtime.RequiredError(
                'kind',
                'Required parameter "kind" was null or undefined when calling addWorkComment().'
            );
        }

        if (requestParameters['contextId'] == null) {
            throw new runtime.RequiredError(
                'contextId',
                'Required parameter "contextId" was null or undefined when calling addWorkComment().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling addWorkComment().'
            );
        }

        if (requestParameters['workCommentInput'] == null) {
            throw new runtime.RequiredError(
                'workCommentInput',
                'Required parameter "workCommentInput" was null or undefined when calling addWorkComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/work/{kind}/{contextId}/comments`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{kind}', encodeURIComponent(String(requestParameters['kind'])));
        urlPath = urlPath.replace('{contextId}', encodeURIComponent(String(requestParameters['contextId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkCommentInputToJSON(requestParameters['workCommentInput']),
        };
    }

    /**
     */
    async addWorkCommentRaw(requestParameters: AddWorkCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.addWorkCommentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async addWorkComment(requestParameters: AddWorkCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.addWorkCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for cancelOnsiteRequirement without sending the request
     */
    async cancelOnsiteRequirementRequestOpts(requestParameters: CancelOnsiteRequirementRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling cancelOnsiteRequirement().'
            );
        }

        if (requestParameters['requirementId'] == null) {
            throw new runtime.RequiredError(
                'requirementId',
                'Required parameter "requirementId" was null or undefined when calling cancelOnsiteRequirement().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling cancelOnsiteRequirement().'
            );
        }

        if (requestParameters['workVersionInput'] == null) {
            throw new runtime.RequiredError(
                'workVersionInput',
                'Required parameter "workVersionInput" was null or undefined when calling cancelOnsiteRequirement().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/requirements/{requirementId}/cancel`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{requirementId}', encodeURIComponent(String(requestParameters['requirementId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkVersionInputToJSON(requestParameters['workVersionInput']),
        };
    }

    /**
     */
    async cancelOnsiteRequirementRaw(requestParameters: CancelOnsiteRequirementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.cancelOnsiteRequirementRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async cancelOnsiteRequirement(requestParameters: CancelOnsiteRequirementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.cancelOnsiteRequirementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createAssignedTask without sending the request
     */
    async createAssignedTaskRequestOpts(requestParameters: CreateAssignedTaskRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling createAssignedTask().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createAssignedTask().'
            );
        }

        if (requestParameters['taskInput'] == null) {
            throw new runtime.RequiredError(
                'taskInput',
                'Required parameter "taskInput" was null or undefined when calling createAssignedTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/tasks`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskInputToJSON(requestParameters['taskInput']),
        };
    }

    /**
     */
    async createAssignedTaskRaw(requestParameters: CreateAssignedTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.createAssignedTaskRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async createAssignedTask(requestParameters: CreateAssignedTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.createAssignedTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createCounterproposal without sending the request
     */
    async createCounterproposalRequestOpts(requestParameters: CreateCounterproposalRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling createCounterproposal().'
            );
        }

        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling createCounterproposal().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createCounterproposal().'
            );
        }

        if (requestParameters['proposalInput'] == null) {
            throw new runtime.RequiredError(
                'proposalInput',
                'Required parameter "proposalInput" was null or undefined when calling createCounterproposal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/requests/{requestId}/proposals`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{requestId}', encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProposalInputToJSON(requestParameters['proposalInput']),
        };
    }

    /**
     */
    async createCounterproposalRaw(requestParameters: CreateCounterproposalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.createCounterproposalRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async createCounterproposal(requestParameters: CreateCounterproposalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.createCounterproposalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createOnsiteRequirement without sending the request
     */
    async createOnsiteRequirementRequestOpts(requestParameters: CreateOnsiteRequirementRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling createOnsiteRequirement().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createOnsiteRequirement().'
            );
        }

        if (requestParameters['onsiteInput'] == null) {
            throw new runtime.RequiredError(
                'onsiteInput',
                'Required parameter "onsiteInput" was null or undefined when calling createOnsiteRequirement().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/requirements`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OnsiteInputToJSON(requestParameters['onsiteInput']),
        };
    }

    /**
     */
    async createOnsiteRequirementRaw(requestParameters: CreateOnsiteRequirementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.createOnsiteRequirementRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async createOnsiteRequirement(requestParameters: CreateOnsiteRequirementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.createOnsiteRequirementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createPlanningDraft without sending the request
     */
    async createPlanningDraftRequestOpts(requestParameters: CreatePlanningDraftRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling createPlanningDraft().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createPlanningDraft().'
            );
        }

        if (requestParameters['draftInput'] == null) {
            throw new runtime.RequiredError(
                'draftInput',
                'Required parameter "draftInput" was null or undefined when calling createPlanningDraft().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/requests`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DraftInputToJSON(requestParameters['draftInput']),
        };
    }

    /**
     */
    async createPlanningDraftRaw(requestParameters: CreatePlanningDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.createPlanningDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async createPlanningDraft(requestParameters: CreatePlanningDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.createPlanningDraftRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for decidePlanningDays without sending the request
     */
    async decidePlanningDaysRequestOpts(requestParameters: DecidePlanningDaysRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling decidePlanningDays().'
            );
        }

        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling decidePlanningDays().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling decidePlanningDays().'
            );
        }

        if (requestParameters['decisionInput'] == null) {
            throw new runtime.RequiredError(
                'decisionInput',
                'Required parameter "decisionInput" was null or undefined when calling decidePlanningDays().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/requests/{requestId}/decide`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{requestId}', encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DecisionInputToJSON(requestParameters['decisionInput']),
        };
    }

    /**
     */
    async decidePlanningDaysRaw(requestParameters: DecidePlanningDaysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.decidePlanningDaysRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async decidePlanningDays(requestParameters: DecidePlanningDaysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.decidePlanningDaysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for editAssignedTask without sending the request
     */
    async editAssignedTaskRequestOpts(requestParameters: EditAssignedTaskRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling editAssignedTask().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling editAssignedTask().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling editAssignedTask().'
            );
        }

        if (requestParameters['taskInput'] == null) {
            throw new runtime.RequiredError(
                'taskInput',
                'Required parameter "taskInput" was null or undefined when calling editAssignedTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/tasks/{taskId}`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{taskId}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TaskInputToJSON(requestParameters['taskInput']),
        };
    }

    /**
     */
    async editAssignedTaskRaw(requestParameters: EditAssignedTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.editAssignedTaskRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async editAssignedTask(requestParameters: EditAssignedTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.editAssignedTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for editOnsiteRequirement without sending the request
     */
    async editOnsiteRequirementRequestOpts(requestParameters: EditOnsiteRequirementRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling editOnsiteRequirement().'
            );
        }

        if (requestParameters['requirementId'] == null) {
            throw new runtime.RequiredError(
                'requirementId',
                'Required parameter "requirementId" was null or undefined when calling editOnsiteRequirement().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling editOnsiteRequirement().'
            );
        }

        if (requestParameters['onsiteInput'] == null) {
            throw new runtime.RequiredError(
                'onsiteInput',
                'Required parameter "onsiteInput" was null or undefined when calling editOnsiteRequirement().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/requirements/{requirementId}`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{requirementId}', encodeURIComponent(String(requestParameters['requirementId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: OnsiteInputToJSON(requestParameters['onsiteInput']),
        };
    }

    /**
     */
    async editOnsiteRequirementRaw(requestParameters: EditOnsiteRequirementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.editOnsiteRequirementRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async editOnsiteRequirement(requestParameters: EditOnsiteRequirementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.editOnsiteRequirementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for editPlanningDraft without sending the request
     */
    async editPlanningDraftRequestOpts(requestParameters: EditPlanningDraftRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling editPlanningDraft().'
            );
        }

        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling editPlanningDraft().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling editPlanningDraft().'
            );
        }

        if (requestParameters['draftInput'] == null) {
            throw new runtime.RequiredError(
                'draftInput',
                'Required parameter "draftInput" was null or undefined when calling editPlanningDraft().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/requests/{requestId}/draft`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{requestId}', encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DraftInputToJSON(requestParameters['draftInput']),
        };
    }

    /**
     */
    async editPlanningDraftRaw(requestParameters: EditPlanningDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.editPlanningDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async editPlanningDraft(requestParameters: EditPlanningDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.editPlanningDraftRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAssignedTask without sending the request
     */
    async getAssignedTaskRequestOpts(requestParameters: GetAssignedTaskRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling getAssignedTask().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling getAssignedTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/planning/{employeeId}/tasks/{taskId}`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{taskId}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getAssignedTaskRaw(requestParameters: GetAssignedTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskView>> {
        const requestOptions = await this.getAssignedTaskRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskViewFromJSON(jsonValue));
    }

    /**
     */
    async getAssignedTask(requestParameters: GetAssignedTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskView> {
        const response = await this.getAssignedTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCalendar without sending the request
     */
    async getCalendarRequestOpts(requestParameters: GetCalendarRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling getCalendar().'
            );
        }

        if (requestParameters['from'] == null) {
            throw new runtime.RequiredError(
                'from',
                'Required parameter "from" was null or undefined when calling getCalendar().'
            );
        }

        if (requestParameters['to'] == null) {
            throw new runtime.RequiredError(
                'to',
                'Required parameter "to" was null or undefined when calling getCalendar().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = runtime.serializeDate(requestParameters['from'] as any);
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = runtime.serializeDate(requestParameters['to'] as any);
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/planning/{employeeId}/calendar`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCalendarRaw(requestParameters: GetCalendarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CalendarView>> {
        const requestOptions = await this.getCalendarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CalendarViewFromJSON(jsonValue));
    }

    /**
     */
    async getCalendar(requestParameters: GetCalendarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CalendarView> {
        const response = await this.getCalendarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOnsiteRequirement without sending the request
     */
    async getOnsiteRequirementRequestOpts(requestParameters: GetOnsiteRequirementRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling getOnsiteRequirement().'
            );
        }

        if (requestParameters['requirementId'] == null) {
            throw new runtime.RequiredError(
                'requirementId',
                'Required parameter "requirementId" was null or undefined when calling getOnsiteRequirement().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/planning/{employeeId}/requirements/{requirementId}`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{requirementId}', encodeURIComponent(String(requestParameters['requirementId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getOnsiteRequirementRaw(requestParameters: GetOnsiteRequirementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OnsiteView>> {
        const requestOptions = await this.getOnsiteRequirementRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OnsiteViewFromJSON(jsonValue));
    }

    /**
     */
    async getOnsiteRequirement(requestParameters: GetOnsiteRequirementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OnsiteView> {
        const response = await this.getOnsiteRequirementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPlanningRequest without sending the request
     */
    async getPlanningRequestRequestOpts(requestParameters: GetPlanningRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling getPlanningRequest().'
            );
        }

        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling getPlanningRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/planning/{employeeId}/requests/{requestId}`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{requestId}', encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getPlanningRequestRaw(requestParameters: GetPlanningRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestView>> {
        const requestOptions = await this.getPlanningRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestViewFromJSON(jsonValue));
    }

    /**
     */
    async getPlanningRequest(requestParameters: GetPlanningRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestView> {
        const response = await this.getPlanningRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAssignedTasks without sending the request
     */
    async listAssignedTasksRequestOpts(requestParameters: ListAssignedTasksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling listAssignedTasks().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/planning/{employeeId}/tasks`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listAssignedTasksRaw(requestParameters: ListAssignedTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskPage>> {
        const requestOptions = await this.listAssignedTasksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskPageFromJSON(jsonValue));
    }

    /**
     */
    async listAssignedTasks(requestParameters: ListAssignedTasksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskPage> {
        const response = await this.listAssignedTasksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCounterproposals without sending the request
     */
    async listCounterproposalsRequestOpts(requestParameters: ListCounterproposalsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling listCounterproposals().'
            );
        }

        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling listCounterproposals().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/planning/{employeeId}/requests/{requestId}/proposals`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{requestId}', encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listCounterproposalsRaw(requestParameters: ListCounterproposalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProposalPage>> {
        const requestOptions = await this.listCounterproposalsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProposalPageFromJSON(jsonValue));
    }

    /**
     */
    async listCounterproposals(requestParameters: ListCounterproposalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProposalPage> {
        const response = await this.listCounterproposalsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listOnsiteRequirements without sending the request
     */
    async listOnsiteRequirementsRequestOpts(requestParameters: ListOnsiteRequirementsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling listOnsiteRequirements().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/planning/{employeeId}/requirements`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listOnsiteRequirementsRaw(requestParameters: ListOnsiteRequirementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OnsitePage>> {
        const requestOptions = await this.listOnsiteRequirementsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OnsitePageFromJSON(jsonValue));
    }

    /**
     */
    async listOnsiteRequirements(requestParameters: ListOnsiteRequirementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OnsitePage> {
        const response = await this.listOnsiteRequirementsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPlanningComments without sending the request
     */
    async listPlanningCommentsRequestOpts(requestParameters: ListPlanningCommentsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling listPlanningComments().'
            );
        }

        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling listPlanningComments().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/planning/{employeeId}/requests/{requestId}/comments`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{requestId}', encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listPlanningCommentsRaw(requestParameters: ListPlanningCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentPage>> {
        const requestOptions = await this.listPlanningCommentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentPageFromJSON(jsonValue));
    }

    /**
     */
    async listPlanningComments(requestParameters: ListPlanningCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentPage> {
        const response = await this.listPlanningCommentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPlanningRequests without sending the request
     */
    async listPlanningRequestsRequestOpts(requestParameters: ListPlanningRequestsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling listPlanningRequests().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/planning/{employeeId}/requests`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listPlanningRequestsRaw(requestParameters: ListPlanningRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestPage>> {
        const requestOptions = await this.listPlanningRequestsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestPageFromJSON(jsonValue));
    }

    /**
     */
    async listPlanningRequests(requestParameters: ListPlanningRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestPage> {
        const response = await this.listPlanningRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWeeklyPatterns without sending the request
     */
    async listWeeklyPatternsRequestOpts(requestParameters: ListWeeklyPatternsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling listWeeklyPatterns().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/planning/{employeeId}/patterns`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listWeeklyPatternsRaw(requestParameters: ListWeeklyPatternsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PatternPage>> {
        const requestOptions = await this.listWeeklyPatternsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PatternPageFromJSON(jsonValue));
    }

    /**
     */
    async listWeeklyPatterns(requestParameters: ListWeeklyPatternsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PatternPage> {
        const response = await this.listWeeklyPatternsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWorkEntries without sending the request
     */
    async listWorkEntriesRequestOpts(requestParameters: ListWorkEntriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling listWorkEntries().'
            );
        }

        if (requestParameters['kind'] == null) {
            throw new runtime.RequiredError(
                'kind',
                'Required parameter "kind" was null or undefined when calling listWorkEntries().'
            );
        }

        if (requestParameters['contextId'] == null) {
            throw new runtime.RequiredError(
                'contextId',
                'Required parameter "contextId" was null or undefined when calling listWorkEntries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/planning/{employeeId}/work/{kind}/{contextId}/entries`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{kind}', encodeURIComponent(String(requestParameters['kind'])));
        urlPath = urlPath.replace('{contextId}', encodeURIComponent(String(requestParameters['contextId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listWorkEntriesRaw(requestParameters: ListWorkEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkEntryPage>> {
        const requestOptions = await this.listWorkEntriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkEntryPageFromJSON(jsonValue));
    }

    /**
     */
    async listWorkEntries(requestParameters: ListWorkEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkEntryPage> {
        const response = await this.listWorkEntriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for previewOnsiteRequirement without sending the request
     */
    async previewOnsiteRequirementRequestOpts(requestParameters: PreviewOnsiteRequirementRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling previewOnsiteRequirement().'
            );
        }

        if (requestParameters['from'] == null) {
            throw new runtime.RequiredError(
                'from',
                'Required parameter "from" was null or undefined when calling previewOnsiteRequirement().'
            );
        }

        if (requestParameters['to'] == null) {
            throw new runtime.RequiredError(
                'to',
                'Required parameter "to" was null or undefined when calling previewOnsiteRequirement().'
            );
        }

        if (requestParameters['location'] == null) {
            throw new runtime.RequiredError(
                'location',
                'Required parameter "location" was null or undefined when calling previewOnsiteRequirement().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = runtime.serializeDate(requestParameters['from'] as any);
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = runtime.serializeDate(requestParameters['to'] as any);
        }

        if (requestParameters['location'] != null) {
            queryParameters['location'] = requestParameters['location'];
        }

        if (requestParameters['excludes'] != null) {
            queryParameters['excludes'] = requestParameters['excludes'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/planning/{employeeId}/onsite-preview`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async previewOnsiteRequirementRaw(requestParameters: PreviewOnsiteRequirementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OnsitePreview>> {
        const requestOptions = await this.previewOnsiteRequirementRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OnsitePreviewFromJSON(jsonValue));
    }

    /**
     */
    async previewOnsiteRequirement(requestParameters: PreviewOnsiteRequirementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OnsitePreview> {
        const response = await this.previewOnsiteRequirementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for previewPlanningDates without sending the request
     */
    async previewPlanningDatesRequestOpts(requestParameters: PreviewPlanningDatesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['from'] == null) {
            throw new runtime.RequiredError(
                'from',
                'Required parameter "from" was null or undefined when calling previewPlanningDates().'
            );
        }

        if (requestParameters['to'] == null) {
            throw new runtime.RequiredError(
                'to',
                'Required parameter "to" was null or undefined when calling previewPlanningDates().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = runtime.serializeDate(requestParameters['from'] as any);
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = runtime.serializeDate(requestParameters['to'] as any);
        }

        if (requestParameters['includeWeekends'] != null) {
            queryParameters['includeWeekends'] = requestParameters['includeWeekends'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/planning/date-preview`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async previewPlanningDatesRaw(requestParameters: PreviewPlanningDatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DatePreview>> {
        const requestOptions = await this.previewPlanningDatesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DatePreviewFromJSON(jsonValue));
    }

    /**
     */
    async previewPlanningDates(requestParameters: PreviewPlanningDatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DatePreview> {
        const response = await this.previewPlanningDatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for reviseCounterproposal without sending the request
     */
    async reviseCounterproposalRequestOpts(requestParameters: ReviseCounterproposalRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling reviseCounterproposal().'
            );
        }

        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling reviseCounterproposal().'
            );
        }

        if (requestParameters['proposalId'] == null) {
            throw new runtime.RequiredError(
                'proposalId',
                'Required parameter "proposalId" was null or undefined when calling reviseCounterproposal().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling reviseCounterproposal().'
            );
        }

        if (requestParameters['proposalInput'] == null) {
            throw new runtime.RequiredError(
                'proposalInput',
                'Required parameter "proposalInput" was null or undefined when calling reviseCounterproposal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/requests/{requestId}/proposals/{proposalId}`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{requestId}', encodeURIComponent(String(requestParameters['requestId'])));
        urlPath = urlPath.replace('{proposalId}', encodeURIComponent(String(requestParameters['proposalId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProposalInputToJSON(requestParameters['proposalInput']),
        };
    }

    /**
     */
    async reviseCounterproposalRaw(requestParameters: ReviseCounterproposalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.reviseCounterproposalRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async reviseCounterproposal(requestParameters: ReviseCounterproposalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.reviseCounterproposalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setWeeklyPattern without sending the request
     */
    async setWeeklyPatternRequestOpts(requestParameters: SetWeeklyPatternRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling setWeeklyPattern().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling setWeeklyPattern().'
            );
        }

        if (requestParameters['patternInput'] == null) {
            throw new runtime.RequiredError(
                'patternInput',
                'Required parameter "patternInput" was null or undefined when calling setWeeklyPattern().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/patterns`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PatternInputToJSON(requestParameters['patternInput']),
        };
    }

    /**
     */
    async setWeeklyPatternRaw(requestParameters: SetWeeklyPatternRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.setWeeklyPatternRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async setWeeklyPattern(requestParameters: SetWeeklyPatternRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.setWeeklyPatternRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for submitPlanningRequest without sending the request
     */
    async submitPlanningRequestRequestOpts(requestParameters: SubmitPlanningRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling submitPlanningRequest().'
            );
        }

        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling submitPlanningRequest().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling submitPlanningRequest().'
            );
        }

        if (requestParameters['submitInput'] == null) {
            throw new runtime.RequiredError(
                'submitInput',
                'Required parameter "submitInput" was null or undefined when calling submitPlanningRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/requests/{requestId}/submit`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{requestId}', encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmitInputToJSON(requestParameters['submitInput']),
        };
    }

    /**
     */
    async submitPlanningRequestRaw(requestParameters: SubmitPlanningRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.submitPlanningRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async submitPlanningRequest(requestParameters: SubmitPlanningRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.submitPlanningRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTaskProgress without sending the request
     */
    async updateTaskProgressRequestOpts(requestParameters: UpdateTaskProgressRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling updateTaskProgress().'
            );
        }

        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling updateTaskProgress().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling updateTaskProgress().'
            );
        }

        if (requestParameters['taskProgressInput'] == null) {
            throw new runtime.RequiredError(
                'taskProgressInput',
                'Required parameter "taskProgressInput" was null or undefined when calling updateTaskProgress().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/tasks/{taskId}/progress`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{taskId}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskProgressInputToJSON(requestParameters['taskProgressInput']),
        };
    }

    /**
     */
    async updateTaskProgressRaw(requestParameters: UpdateTaskProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.updateTaskProgressRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async updateTaskProgress(requestParameters: UpdateTaskProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.updateTaskProgressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for withdrawPlanningDays without sending the request
     */
    async withdrawPlanningDaysRequestOpts(requestParameters: WithdrawPlanningDaysRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['employeeId'] == null) {
            throw new runtime.RequiredError(
                'employeeId',
                'Required parameter "employeeId" was null or undefined when calling withdrawPlanningDays().'
            );
        }

        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling withdrawPlanningDays().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling withdrawPlanningDays().'
            );
        }

        if (requestParameters['withdrawInput'] == null) {
            throw new runtime.RequiredError(
                'withdrawInput',
                'Required parameter "withdrawInput" was null or undefined when calling withdrawPlanningDays().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/api/v1/planning/{employeeId}/requests/{requestId}/withdraw`;
        urlPath = urlPath.replace('{employeeId}', encodeURIComponent(String(requestParameters['employeeId'])));
        urlPath = urlPath.replace('{requestId}', encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WithdrawInputToJSON(requestParameters['withdrawInput']),
        };
    }

    /**
     */
    async withdrawPlanningDaysRaw(requestParameters: WithdrawPlanningDaysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MutationReceipt>> {
        const requestOptions = await this.withdrawPlanningDaysRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MutationReceiptFromJSON(jsonValue));
    }

    /**
     */
    async withdrawPlanningDays(requestParameters: WithdrawPlanningDaysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MutationReceipt> {
        const response = await this.withdrawPlanningDaysRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
