/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type WorkspaceInfo,
    WorkspaceInfoFromJSON,
    WorkspaceInfoToJSON,
} from '../models/WorkspaceInfo';

/**
 *
 */
export class WorkspaceApi extends runtime.BaseAPI {

    /**
     * Creates request options for getWorkspaceInfo without sending the request
     */
    async getWorkspaceInfoRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/workspace`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Public workspace metadata and a fresh server timestamp; no personal data.
     */
    async getWorkspaceInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkspaceInfo>> {
        const requestOptions = await this.getWorkspaceInfoRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkspaceInfoFromJSON(jsonValue));
    }

    /**
     * Public workspace metadata and a fresh server timestamp; no personal data.
     */
    async getWorkspaceInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkspaceInfo> {
        const response = await this.getWorkspaceInfoRaw(initOverrides);
        return await response.value();
    }

}
