// <auto-generated />
using System;
using HomeOffice.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeOffice.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HomeOfficeDbContext))]
    [Migration("20260910230508_AccessInvitations")]
    partial class AccessInvitations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeOffice.Domain.Access.AccessAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("ActorMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ActorMemberId");

                    b.HasIndex("OrganizationId", "MemberId");

                    b.HasIndex("OrganizationId", "CreatedAt", "Id");

                    b.ToTable("AccessAudits", null, t =>
                        {
                            t.HasCheckConstraint("CK_AccessAudit_Source", "(\"Source\" IN ('operator', 'anonymous', 'worker') AND \"ActorMemberId\" IS NULL) OR (\"Source\" = 'administrator' AND \"ActorMemberId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("HomeOffice.Domain.Access.AccessInvitation", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CodeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreationFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryState")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("LastRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProtectedCode")
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)");

                    b.Property<int>("RequestsInWindow")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("WindowStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MemberId");

                    b.HasIndex("DeliveryState", "NextAttemptAt");

                    b.HasIndex("OrganizationId", "CreatedBy");

                    b.HasIndex("OrganizationId", "MemberId");

                    b.ToTable("AccessInvitations", (string)null);
                });

            modelBuilder.Entity("HomeOffice.Domain.Access.InvitationCommand", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpectedVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("OrganizationId", "ActorId", "CommandId");

                    b.HasIndex("OrganizationId", "MemberId");

                    b.ToTable("InvitationCommands", (string)null);
                });

            modelBuilder.Entity("HomeOffice.Domain.Access.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAccountAdministrator")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManager")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("HomeOffice.Domain.Access.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PlanningTimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("HomeOffice.Domain.Access.ReportingLine", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("EmployeeId");

                    b.HasIndex("OrganizationId", "EmployeeId");

                    b.HasIndex("OrganizationId", "ManagerId");

                    b.ToTable("ReportingLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReportingLine_NoSelf", "\"EmployeeId\" <> \"ManagerId\"");
                        });
                });

            modelBuilder.Entity("HomeOffice.Domain.Notifications.InboxNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Context")
                        .HasColumnType("integer");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("Historical")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "RecipientId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EmployeeId");

                    b.HasIndex("RecipientId", "Historical", "CreatedAt", "Id");

                    b.ToTable("InboxNotification");
                });

            modelBuilder.Entity("HomeOffice.Domain.Notifications.PushDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeviceReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DeviceVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastError")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ProviderAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId", "InstallationId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "RecipientId", "InstallationId");

                    b.HasIndex("OrganizationId", "RecipientId", "NotificationId");

                    b.HasIndex("State", "NextAttemptAt", "LeaseUntil");

                    b.ToTable("PushDelivery", null, t =>
                        {
                            t.HasCheckConstraint("CK_PushDelivery", "\"State\" BETWEEN 0 AND 5 AND \"Attempts\" >= 0 AND \"DeviceVersion\" > 0 AND (\"State\" <> 1 OR (\"LeaseId\" IS NOT NULL AND \"LeaseUntil\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("HomeOffice.Domain.Notifications.PushDevice", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("AddressHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProtectedAddress")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("InstallationId");

                    b.HasIndex("AddressHash")
                        .IsUnique()
                        .HasFilter("\"Active\"");

                    b.HasIndex("MemberId", "Active", "ExpiresAt");

                    b.ToTable("PushDevice", null, t =>
                        {
                            t.HasCheckConstraint("CK_PushDevice", "\"Version\" > 0 AND \"Provider\" IN (1,2)");
                        });
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.AssignedTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProgressNote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("RequirementId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresOnsite")
                        .HasColumnType("boolean");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Deadline", "Id");

                    b.HasIndex("OrganizationId", "EmployeeId", "RequirementId");

                    b.ToTable("AssignedTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_Task", "\"Version\" > 0 AND \"State\" BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.ChangeProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedRequestId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("AffectedDayIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.PrimitiveCollection<long[]>("AffectedDayVersions")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DaysJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RequirementId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RequirementRevision")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "Revision")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EmployeeId", "RequestId");

                    b.HasIndex("OrganizationId", "EmployeeId", "RequirementId");

                    b.ToTable("ChangeProposals", null, t =>
                        {
                            t.HasCheckConstraint("CK_Proposal", "\"Revision\" > 0 AND \"State\" BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.OnsiteAcknowledgement", b =>
                {
                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequirementId", "Revision");

                    b.HasIndex("OrganizationId", "EmployeeId", "RequirementId");

                    b.ToTable("OnsiteAcknowledgement");
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.OnsiteRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "From", "To");

                    b.ToTable("OnsiteRequirements", null, t =>
                        {
                            t.HasCheckConstraint("CK_Onsite", "\"To\" >= \"From\" AND \"Revision\" > 0 AND \"Version\" > 0 AND \"State\" BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.PlanDay", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<int>("Availability")
                        .HasColumnType("integer");

                    b.Property<Guid>("DecidedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Location")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceDayId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("EmployeeId", "LocalDate");

                    b.HasIndex("OrganizationId", "EmployeeId", "SourceDayId");

                    b.ToTable("PlanDays", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlanDay", "\"Version\" > 0 AND ((\"Availability\" = 0 AND \"Location\" IN (1,2)) OR (\"Availability\" IN (1,2) AND \"Location\" = 0))");
                        });
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.PlanningAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<long>("CalendarVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("ChangedDaysJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "CalendarVersion")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EmployeeId");

                    b.ToTable("PlanningAudit");
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.PlanningComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProposalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EmployeeId", "ProposalId");

                    b.HasIndex("OrganizationId", "EmployeeId", "RequestId");

                    b.HasIndex("RequestId", "CreatedAt", "Id");

                    b.ToTable("PlanningComment");
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.PlanningOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<long>("CalendarVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Historical")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "CalendarVersion")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EmployeeId");

                    b.HasIndex("State", "NextAttemptAt", "LeaseUntil");

                    b.ToTable("PlanningOutbox", null, t =>
                        {
                            t.HasCheckConstraint("CK_OutboxProcessing", "\"State\" BETWEEN 0 AND 4 AND \"Attempts\" >= 0 AND (\"State\" <> 1 OR (\"LeaseId\" IS NOT NULL AND \"LeaseUntil\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.PlanningProfile", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<long>("CalendarVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("EmployeeId");

                    b.ToTable("PlanningProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProfileVersion", "\"CalendarVersion\" >= 0");
                        });
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.PlanningReceipt", b =>
                {
                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Operation")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ActorId", "Operation", "Key");

                    b.ToTable("PlanningReceipt");
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.PlanningRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedProposalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentRevisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<Guid>("RootId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RootId", "Revision")
                        .IsUnique();

                    b.HasIndex("EmployeeId", "CreatedAt", "Id");

                    b.HasIndex("OrganizationId", "EmployeeId", "ParentRevisionId");

                    b.ToTable("PlanningRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_Request", "\"Version\" > 0 AND \"Revision\" > 0 AND \"State\" BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.ProposalAcknowledgement", b =>
                {
                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.HasKey("ProposalId");

                    b.HasIndex("OrganizationId", "EmployeeId", "ProposalId");

                    b.ToTable("ProposalAcknowledgement");
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.RequestedDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Availability")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BaseDayId")
                        .HasColumnType("uuid");

                    b.Property<long?>("BasePlanVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("Cancel")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<int>("Location")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ReservesDate")
                        .HasColumnType("boolean");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "LocalDate")
                        .IsUnique()
                        .HasFilter("\"ReservesDate\"");

                    b.HasIndex("RequestId", "LocalDate")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EmployeeId", "BaseDayId");

                    b.HasIndex("OrganizationId", "EmployeeId", "RequestId");

                    b.ToTable("RequestedDays", null, t =>
                        {
                            t.HasCheckConstraint("CK_Day", "\"Version\" > 0 AND \"Location\" BETWEEN 0 AND 2 AND \"Availability\" BETWEEN 0 AND 2 AND \"Decision\" BETWEEN 0 AND 5 AND (NOT \"ReservesDate\" OR \"Decision\" = 0)");

                            t.HasCheckConstraint("CK_DayBase", "(\"BaseDayId\" IS NULL) = (\"BasePlanVersion\" IS NULL) AND (NOT \"Cancel\" OR \"BaseDayId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.WeeklyPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("Locations")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "EffectiveFrom")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "EmployeeId");

                    b.ToTable("WeeklyPatterns", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pattern", "cardinality(\"Locations\") = 7 AND \"Locations\" <@ ARRAY[0,1,2] AND \"Version\" > 0");
                        });
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.WorkEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<long>("CalendarVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RequirementId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EmployeeId", "RequirementId");

                    b.HasIndex("OrganizationId", "EmployeeId", "TaskId");

                    b.HasIndex("RequirementId", "CreatedAt", "Id");

                    b.HasIndex("TaskId", "CreatedAt", "Id");

                    b.ToTable("WorkEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkContext", "(\"RequirementId\" IS NULL) <> (\"TaskId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HomeOffice.Domain.Access.AccessAudit", b =>
                {
                    b.HasOne("HomeOffice.Domain.Access.Member", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ActorMemberId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HomeOffice.Domain.Access.Member", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "MemberId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Access.AccessInvitation", b =>
                {
                    b.HasOne("HomeOffice.Domain.Access.Member", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CreatedBy")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HomeOffice.Domain.Access.Member", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "MemberId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Access.InvitationCommand", b =>
                {
                    b.HasOne("HomeOffice.Domain.Access.Member", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ActorId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Access.Member", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "MemberId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Access.Member", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Access.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Access.ReportingLine", b =>
                {
                    b.HasOne("HomeOffice.Domain.Access.Member", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Access.Member", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ManagerId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Notifications.InboxNotification", b =>
                {
                    b.HasOne("HomeOffice.Domain.Planning.PlanningOutbox", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Access.Member", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Access.Member", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "RecipientId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Notifications.PushDelivery", b =>
                {
                    b.HasOne("HomeOffice.Domain.Access.Member", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "RecipientId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Notifications.PushDevice", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "RecipientId", "InstallationId")
                        .HasPrincipalKey("OrganizationId", "MemberId", "InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Notifications.InboxNotification", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "RecipientId", "NotificationId")
                        .HasPrincipalKey("OrganizationId", "RecipientId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Notifications.PushDevice", b =>
                {
                    b.HasOne("HomeOffice.Domain.Access.Member", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "MemberId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.AssignedTask", b =>
                {
                    b.HasOne("HomeOffice.Domain.Planning.PlanningProfile", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Planning.OnsiteRequirement", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId", "RequirementId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.ChangeProposal", b =>
                {
                    b.HasOne("HomeOffice.Domain.Planning.PlanningProfile", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Planning.PlanningRequest", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId", "RequestId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Planning.OnsiteRequirement", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId", "RequirementId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.OnsiteAcknowledgement", b =>
                {
                    b.HasOne("HomeOffice.Domain.Planning.PlanningProfile", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Planning.OnsiteRequirement", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId", "RequirementId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.OnsiteRequirement", b =>
                {
                    b.HasOne("HomeOffice.Domain.Planning.PlanningProfile", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.PlanDay", b =>
                {
                    b.HasOne("HomeOffice.Domain.Planning.PlanningProfile", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Planning.RequestedDay", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId", "SourceDayId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.PlanningAudit", b =>
                {
                    b.HasOne("HomeOffice.Domain.Planning.PlanningProfile", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.PlanningComment", b =>
                {
                    b.HasOne("HomeOffice.Domain.Planning.PlanningProfile", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Planning.ChangeProposal", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId", "ProposalId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HomeOffice.Domain.Planning.PlanningRequest", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId", "RequestId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.PlanningOutbox", b =>
                {
                    b.HasOne("HomeOffice.Domain.Planning.PlanningProfile", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.PlanningProfile", b =>
                {
                    b.HasOne("HomeOffice.Domain.Access.Member", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.PlanningReceipt", b =>
                {
                    b.HasOne("HomeOffice.Domain.Access.Member", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.PlanningRequest", b =>
                {
                    b.HasOne("HomeOffice.Domain.Planning.PlanningProfile", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Planning.PlanningRequest", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId", "ParentRevisionId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.ProposalAcknowledgement", b =>
                {
                    b.HasOne("HomeOffice.Domain.Planning.PlanningProfile", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Planning.ChangeProposal", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId", "ProposalId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.RequestedDay", b =>
                {
                    b.HasOne("HomeOffice.Domain.Planning.PlanningProfile", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Planning.RequestedDay", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId", "BaseDayId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HomeOffice.Domain.Planning.PlanningRequest", null)
                        .WithMany("Days")
                        .HasForeignKey("OrganizationId", "EmployeeId", "RequestId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.WeeklyPattern", b =>
                {
                    b.HasOne("HomeOffice.Domain.Planning.PlanningProfile", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.WorkEntry", b =>
                {
                    b.HasOne("HomeOffice.Domain.Planning.PlanningProfile", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeOffice.Domain.Planning.OnsiteRequirement", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId", "RequirementId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HomeOffice.Domain.Planning.AssignedTask", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EmployeeId", "TaskId")
                        .HasPrincipalKey("OrganizationId", "EmployeeId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeOffice.Domain.Planning.PlanningRequest", b =>
                {
                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
