#!/usr/bin/env python3
"""Generate shared Web/Flutter colour tokens and check their accessible pairings."""
import argparse
import json
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def luminance(hex_color):
    channels = [int(hex_color[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    linear = [v / 12.92 if v <= .04045 else ((v + .055) / 1.055) ** 2.4 for v in channels]
    return sum(a * b for a, b in zip(linear, (.2126, .7152, .0722)))


def contrast(a, b):
    high, low = sorted((luminance(a), luminance(b)), reverse=True)
    return (high + .05) / (low + .05)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    tokens = json.loads((ROOT / 'design/tokens.json').read_text(encoding='utf-8'))
    font = json.loads((ROOT / 'design/font-source.json').read_text(encoding='utf-8'))
    for area in ('web/public', 'mobile/assets'):
        folder = ROOT / f'apps/{area}/fonts'
        if hashlib.sha256((folder / 'Outfit.ttf').read_bytes()).hexdigest() != font['sha256']:
            raise SystemExit(f'Font checksum mismatch: {area}')
        if 'SIL OPEN FONT LICENSE Version 1.1' not in (folder / 'OFL.txt').read_text(encoding='utf-8'):
            raise SystemExit(f'Missing font license: {area}')
    css = '/* Generated by scripts/generate_theme.py. Edit design/tokens.json. */\n'
    dart = '// Generated by scripts/generate_theme.py. Edit design/tokens.json.\n'
    dart += "import 'package:flutter/material.dart';\n\nclass ThemeTokens {\n  const ThemeTokens(this.dark);\n  final bool dark;\n"
    report = {}
    for mode in ('light', 'dark'):
        t = tokens[mode]
        css += (':root,\n:root[data-theme="light"]' if mode == 'light' else ':root[data-theme="dark"]') + ' {\n'
        css += f'  color-scheme: {mode};\n'
        css += ''.join(f'  --{key}: {value};\n' for key, value in t.items()) + '}\n'
        pairs = [(fg, bg, 4.5) for fg, bg in [
            ('foreground', 'background'), ('foreground', 'surface'), ('foreground', 'popover'),
            ('foreground', 'accent'),
            ('muted-foreground', 'background'), ('muted-foreground', 'surface'), ('muted-foreground', 'muted'),
            ('primary-foreground', 'primary'), ('primary', 'surface'), ('primary', 'popover'),
            ('secondary-foreground', 'secondary'), ('pending', 'pending-surface'),
            ('danger', 'danger-surface'), ('info', 'info-surface')]]
        pairs += [(fg, bg, 3) for fg in ('ring', 'input') for bg in ('surface', 'popover', 'background')]
        report[mode] = {}
        for fg, bg, minimum in pairs:
            ratio = contrast(t[fg], t[bg])
            report[mode][f'{fg} / {bg}'] = round(ratio, 2)
            if ratio < minimum:
                raise SystemExit(f'{mode}: {fg}/{bg} contrast {ratio:.2f} < {minimum}')
    for key, value in tokens['light'].items():
        name = key.split('-')[0] + ''.join(s.title() for s in key.split('-')[1:])
        expression = f"dark ? const Color(0xff{tokens['dark'][key][1:]}) : const Color(0xff{value[1:]});"
        line = f"  Color get {name} => {expression}"
        dart += (line if len(line) <= 80 else f"  Color get {name} =>\n      {expression}") + '\n'
    dart += '}\n'
    outputs = {
        'apps/web/src/theme/tokens.css': css,
        'apps/mobile/lib/theme/theme_tokens.dart': dart,
        'design/contrast.json': json.dumps(report, indent=2) + '\n',
    }
    for name, content in outputs.items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                raise SystemExit(f'Theme drift: run python scripts/generate_theme.py ({name})')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8')
    print('Shared theme tokens/contrast: OK (both modes; text >=4.5, controls/focus >=3).')


if __name__ == '__main__':
    main()
