/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AcceptProposalInput
 */
export interface AcceptProposalInput {
    /**
     *
     */
    expectedCalendarVersion: number | null;
    /**
     *
     */
    expectedProposalRevision: number;
}

/**
 * Check if a given object implements the AcceptProposalInput interface.
 */
export function instanceOfAcceptProposalInput(value: object): value is AcceptProposalInput {
    if (!('expectedCalendarVersion' in value) || value['expectedCalendarVersion'] === undefined) return false;
    if (!('expectedProposalRevision' in value) || value['expectedProposalRevision'] === undefined) return false;
    return true;
}

export function AcceptProposalInputFromJSON(json: any): AcceptProposalInput {
    return AcceptProposalInputFromJSONTyped(json, false);
}

export function AcceptProposalInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptProposalInput {
    if (json == null) {
        return json;
    }
    return {

        'expectedCalendarVersion': json['expectedCalendarVersion'],
        'expectedProposalRevision': json['expectedProposalRevision'],
    };
}

export function AcceptProposalInputToJSON(json: any): AcceptProposalInput {
    return AcceptProposalInputToJSONTyped(json, false);
}

export function AcceptProposalInputToJSONTyped(value?: AcceptProposalInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'expectedCalendarVersion': value['expectedCalendarVersion'],
        'expectedProposalRevision': value['expectedProposalRevision'],
    };
}
