/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { EffectiveDay } from './EffectiveDay';
import {
    EffectiveDayFromJSON,
    EffectiveDayFromJSONTyped,
    EffectiveDayToJSON,
    EffectiveDayToJSONTyped,
} from './EffectiveDay';
import type { OnsiteView } from './OnsiteView';
import {
    OnsiteViewFromJSON,
    OnsiteViewFromJSONTyped,
    OnsiteViewToJSON,
    OnsiteViewToJSONTyped,
} from './OnsiteView';
import type { PendingDay } from './PendingDay';
import {
    PendingDayFromJSON,
    PendingDayFromJSONTyped,
    PendingDayToJSON,
    PendingDayToJSONTyped,
} from './PendingDay';

/**
 *
 * @export
 * @interface CalendarView
 */
export interface CalendarView {
    /**
     *
     */
    calendarVersion: number;
    /**
     *
     */
    effectiveDays: Array<EffectiveDay>;
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    from: Date;
    /**
     *
     */
    pendingDays: Array<PendingDay>;
    /**
     *
     */
    planningTimeZone: string;
    /**
     *
     */
    requirements: Array<OnsiteView>;
    /**
     *
     */
    to: Date;
}

/**
 * Check if a given object implements the CalendarView interface.
 */
export function instanceOfCalendarView(value: object): value is CalendarView {
    if (!('calendarVersion' in value) || value['calendarVersion'] === undefined) return false;
    if (!('effectiveDays' in value) || value['effectiveDays'] === undefined) return false;
    if (!('employeeId' in value) || value['employeeId'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('pendingDays' in value) || value['pendingDays'] === undefined) return false;
    if (!('planningTimeZone' in value) || value['planningTimeZone'] === undefined) return false;
    if (!('requirements' in value) || value['requirements'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function CalendarViewFromJSON(json: any): CalendarView {
    return CalendarViewFromJSONTyped(json, false);
}

export function CalendarViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalendarView {
    if (json == null) {
        return json;
    }
    return {

        'calendarVersion': json['calendarVersion'],
        'effectiveDays': ((json['effectiveDays'] as Array<any>).map(EffectiveDayFromJSON)),
        'employeeId': json['employeeId'],
        'from': (json['from'] == null ? json['from'] : parseDate(json['from'])),
        'pendingDays': ((json['pendingDays'] as Array<any>).map(PendingDayFromJSON)),
        'planningTimeZone': json['planningTimeZone'],
        'requirements': ((json['requirements'] as Array<any>).map(OnsiteViewFromJSON)),
        'to': (json['to'] == null ? json['to'] : parseDate(json['to'])),
    };
}

export function CalendarViewToJSON(json: any): CalendarView {
    return CalendarViewToJSONTyped(json, false);
}

export function CalendarViewToJSONTyped(value?: CalendarView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'calendarVersion': value['calendarVersion'],
        'effectiveDays': ((value['effectiveDays'] as Array<any>).map(EffectiveDayToJSON)),
        'employeeId': value['employeeId'],
        'from': value['from'] == null ? value['from'] : serializeDate(value['from']),
        'pendingDays': ((value['pendingDays'] as Array<any>).map(PendingDayToJSON)),
        'planningTimeZone': value['planningTimeZone'],
        'requirements': ((value['requirements'] as Array<any>).map(OnsiteViewToJSON)),
        'to': value['to'] == null ? value['to'] : serializeDate(value['to']),
    };
}
