/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommentView } from './CommentView';
import {
    CommentViewFromJSON,
    CommentViewFromJSONTyped,
    CommentViewToJSON,
    CommentViewToJSONTyped,
} from './CommentView';

/**
 *
 * @export
 * @interface CommentPage
 */
export interface CommentPage {
    /**
     *
     */
    items: Array<CommentView>;
    /**
     *
     */
    nextOffset: number | null;
}

/**
 * Check if a given object implements the CommentPage interface.
 */
export function instanceOfCommentPage(value: object): value is CommentPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextOffset' in value) || value['nextOffset'] === undefined) return false;
    return true;
}

export function CommentPageFromJSON(json: any): CommentPage {
    return CommentPageFromJSONTyped(json, false);
}

export function CommentPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentPage {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(CommentViewFromJSON)),
        'nextOffset': json['nextOffset'],
    };
}

export function CommentPageToJSON(json: any): CommentPage {
    return CommentPageToJSONTyped(json, false);
}

export function CommentPageToJSONTyped(value?: CommentPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(CommentViewToJSON)),
        'nextOffset': value['nextOffset'],
    };
}
