/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface CommentView
 */
export interface CommentView {
    /**
     *
     */
    authorId: string;
    /**
     *
     */
    createdAt: Date;
    /**
     *
     */
    id: string;
    /**
     *
     */
    proposalId: string | null;
    /**
     *
     */
    requestId: string;
    /**
     *
     */
    text: string;
}

/**
 * Check if a given object implements the CommentView interface.
 */
export function instanceOfCommentView(value: object): value is CommentView {
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('proposalId' in value) || value['proposalId'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function CommentViewFromJSON(json: any): CommentView {
    return CommentViewFromJSONTyped(json, false);
}

export function CommentViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentView {
    if (json == null) {
        return json;
    }
    return {

        'authorId': json['authorId'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'id': json['id'],
        'proposalId': json['proposalId'],
        'requestId': json['requestId'],
        'text': json['text'],
    };
}

export function CommentViewToJSON(json: any): CommentView {
    return CommentViewToJSONTyped(json, false);
}

export function CommentViewToJSONTyped(value?: CommentView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'authorId': value['authorId'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'id': value['id'],
        'proposalId': value['proposalId'],
        'requestId': value['requestId'],
        'text': value['text'],
    };
}
