/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const DayDecision = {
    Pending: 'Pending',
    Approved: 'Approved',
    Rejected: 'Rejected',
    Withdrawn: 'Withdrawn',
    Superseded: 'Superseded',
    Cancelled: 'Cancelled',
} as const;
export type DayDecision = typeof DayDecision[keyof typeof DayDecision];


export function instanceOfDayDecision(value: any): boolean {
    for (const key in DayDecision) {
        if (Object.prototype.hasOwnProperty.call(DayDecision, key)) {
            if (DayDecision[key as keyof typeof DayDecision] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DayDecisionFromJSON(json: any): DayDecision {
    return DayDecisionFromJSONTyped(json, false);
}

export function DayDecisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DayDecision {
    return json as DayDecision;
}

export function DayDecisionToJSON(value?: DayDecision | null): any {
    return value as any;
}

export function DayDecisionToJSONTyped(value: any, ignoreDiscriminator: boolean): DayDecision {
    return value as DayDecision;
}
