/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SelectedDay } from './SelectedDay';
import {
    SelectedDayFromJSON,
    SelectedDayFromJSONTyped,
    SelectedDayToJSON,
    SelectedDayToJSONTyped,
} from './SelectedDay';

/**
 *
 * @export
 * @interface DecisionInput
 */
export interface DecisionInput {
    /**
     *
     */
    approve: boolean;
    /**
     *
     */
    days: Array<SelectedDay>;
    /**
     *
     */
    expectedCalendarVersion: number | null;
    /**
     *
     */
    expectedRequestVersion: number | null;
    /**
     *
     */
    reason: string | null;
}

/**
 * Check if a given object implements the DecisionInput interface.
 */
export function instanceOfDecisionInput(value: object): value is DecisionInput {
    if (!('approve' in value) || value['approve'] === undefined) return false;
    if (!('days' in value) || value['days'] === undefined) return false;
    if (!('expectedCalendarVersion' in value) || value['expectedCalendarVersion'] === undefined) return false;
    if (!('expectedRequestVersion' in value) || value['expectedRequestVersion'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function DecisionInputFromJSON(json: any): DecisionInput {
    return DecisionInputFromJSONTyped(json, false);
}

export function DecisionInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecisionInput {
    if (json == null) {
        return json;
    }
    return {

        'approve': json['approve'],
        'days': ((json['days'] as Array<any>).map(SelectedDayFromJSON)),
        'expectedCalendarVersion': json['expectedCalendarVersion'],
        'expectedRequestVersion': json['expectedRequestVersion'],
        'reason': json['reason'],
    };
}

export function DecisionInputToJSON(json: any): DecisionInput {
    return DecisionInputToJSONTyped(json, false);
}

export function DecisionInputToJSONTyped(value?: DecisionInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'approve': value['approve'],
        'days': ((value['days'] as Array<any>).map(SelectedDayToJSON)),
        'expectedCalendarVersion': value['expectedCalendarVersion'],
        'expectedRequestVersion': value['expectedRequestVersion'],
        'reason': value['reason'],
    };
}
