/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DeviceReceiptInput
 */
export interface DeviceReceiptInput {
    /**
     *
     */
    installationId: string;
}

/**
 * Check if a given object implements the DeviceReceiptInput interface.
 */
export function instanceOfDeviceReceiptInput(value: object): value is DeviceReceiptInput {
    if (!('installationId' in value) || value['installationId'] === undefined) return false;
    return true;
}

export function DeviceReceiptInputFromJSON(json: any): DeviceReceiptInput {
    return DeviceReceiptInputFromJSONTyped(json, false);
}

export function DeviceReceiptInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceReceiptInput {
    if (json == null) {
        return json;
    }
    return {

        'installationId': json['installationId'],
    };
}

export function DeviceReceiptInputToJSON(json: any): DeviceReceiptInput {
    return DeviceReceiptInputToJSONTyped(json, false);
}

export function DeviceReceiptInputToJSONTyped(value?: DeviceReceiptInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'installationId': value['installationId'],
    };
}
