/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PushProvider } from './PushProvider';
import {
    PushProviderFromJSON,
    PushProviderFromJSONTyped,
    PushProviderToJSON,
    PushProviderToJSONTyped,
} from './PushProvider';

/**
 *
 * @export
 * @interface DeviceRegistrationInput
 */
export interface DeviceRegistrationInput {
    /**
     *
     */
    address: string;
    /**
     *
     */
    expectedVersion: number | null;
    /**
     *
     */
    installationId: string;
    /**
     *
     */
    provider: PushProvider;
}



/**
 * Check if a given object implements the DeviceRegistrationInput interface.
 */
export function instanceOfDeviceRegistrationInput(value: object): value is DeviceRegistrationInput {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('expectedVersion' in value) || value['expectedVersion'] === undefined) return false;
    if (!('installationId' in value) || value['installationId'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function DeviceRegistrationInputFromJSON(json: any): DeviceRegistrationInput {
    return DeviceRegistrationInputFromJSONTyped(json, false);
}

export function DeviceRegistrationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceRegistrationInput {
    if (json == null) {
        return json;
    }
    return {

        'address': json['address'],
        'expectedVersion': json['expectedVersion'],
        'installationId': json['installationId'],
        'provider': PushProviderFromJSON(json['provider']),
    };
}

export function DeviceRegistrationInputToJSON(json: any): DeviceRegistrationInput {
    return DeviceRegistrationInputToJSONTyped(json, false);
}

export function DeviceRegistrationInputToJSONTyped(value?: DeviceRegistrationInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'address': value['address'],
        'expectedVersion': value['expectedVersion'],
        'installationId': value['installationId'],
        'provider': PushProviderToJSON(value['provider']),
    };
}
