/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { PushProvider } from './PushProvider';
import {
    PushProviderFromJSON,
    PushProviderFromJSONTyped,
    PushProviderToJSON,
    PushProviderToJSONTyped,
} from './PushProvider';

/**
 *
 * @export
 * @interface DeviceRegistrationView
 */
export interface DeviceRegistrationView {
    /**
     *
     */
    expiresAt: Date;
    /**
     *
     */
    installationId: string;
    /**
     *
     */
    provider: PushProvider;
    /**
     *
     */
    version: number;
}



/**
 * Check if a given object implements the DeviceRegistrationView interface.
 */
export function instanceOfDeviceRegistrationView(value: object): value is DeviceRegistrationView {
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('installationId' in value) || value['installationId'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function DeviceRegistrationViewFromJSON(json: any): DeviceRegistrationView {
    return DeviceRegistrationViewFromJSONTyped(json, false);
}

export function DeviceRegistrationViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceRegistrationView {
    if (json == null) {
        return json;
    }
    return {

        'expiresAt': (json['expiresAt'] == null ? json['expiresAt'] : parseDateTime(json['expiresAt'])),
        'installationId': json['installationId'],
        'provider': PushProviderFromJSON(json['provider']),
        'version': json['version'],
    };
}

export function DeviceRegistrationViewToJSON(json: any): DeviceRegistrationView {
    return DeviceRegistrationViewToJSONTyped(json, false);
}

export function DeviceRegistrationViewToJSONTyped(value?: DeviceRegistrationView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
        'installationId': value['installationId'],
        'provider': PushProviderToJSON(value['provider']),
        'version': value['version'],
    };
}
