/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { Availability } from './Availability';
import {
    AvailabilityFromJSON,
    AvailabilityFromJSONTyped,
    AvailabilityToJSON,
    AvailabilityToJSONTyped,
} from './Availability';
import type { WorkLocation } from './WorkLocation';
import {
    WorkLocationFromJSON,
    WorkLocationFromJSONTyped,
    WorkLocationToJSON,
    WorkLocationToJSONTyped,
} from './WorkLocation';

/**
 *
 * @export
 * @interface EffectiveDay
 */
export interface EffectiveDay {
    /**
     *
     */
    availability: Availability | null;
    /**
     *
     */
    decidedBy: string | null;
    /**
     *
     */
    localDate: Date;
    /**
     *
     */
    location: WorkLocation;
    /**
     *
     */
    origin: string;
    /**
     *
     */
    sourceDayId: string | null;
    /**
     *
     */
    sourceRequestId: string | null;
    /**
     *
     */
    version: number;
}



/**
 * Check if a given object implements the EffectiveDay interface.
 */
export function instanceOfEffectiveDay(value: object): value is EffectiveDay {
    if (!('availability' in value) || value['availability'] === undefined) return false;
    if (!('decidedBy' in value) || value['decidedBy'] === undefined) return false;
    if (!('localDate' in value) || value['localDate'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('origin' in value) || value['origin'] === undefined) return false;
    if (!('sourceDayId' in value) || value['sourceDayId'] === undefined) return false;
    if (!('sourceRequestId' in value) || value['sourceRequestId'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function EffectiveDayFromJSON(json: any): EffectiveDay {
    return EffectiveDayFromJSONTyped(json, false);
}

export function EffectiveDayFromJSONTyped(json: any, ignoreDiscriminator: boolean): EffectiveDay {
    if (json == null) {
        return json;
    }
    return {

        'availability': AvailabilityFromJSON(json['availability']),
        'decidedBy': json['decidedBy'],
        'localDate': (json['localDate'] == null ? json['localDate'] : parseDate(json['localDate'])),
        'location': WorkLocationFromJSON(json['location']),
        'origin': json['origin'],
        'sourceDayId': json['sourceDayId'],
        'sourceRequestId': json['sourceRequestId'],
        'version': json['version'],
    };
}

export function EffectiveDayToJSON(json: any): EffectiveDay {
    return EffectiveDayToJSONTyped(json, false);
}

export function EffectiveDayToJSONTyped(value?: EffectiveDay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'availability': AvailabilityToJSON(value['availability']),
        'decidedBy': value['decidedBy'],
        'localDate': value['localDate'] == null ? value['localDate'] : serializeDate(value['localDate']),
        'location': WorkLocationToJSON(value['location']),
        'origin': value['origin'],
        'sourceDayId': value['sourceDayId'],
        'sourceRequestId': value['sourceRequestId'],
        'version': value['version'],
    };
}
