/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface InvitationProfile
 */
export interface InvitationProfile {
    /**
     *
     */
    acceptedAt: Date | null;
    /**
     *
     */
    accessVersion: number;
    /**
     *
     */
    active: boolean;
    /**
     *
     */
    cancelledAt: Date | null;
    /**
     *
     */
    codeExpiresAt: Date | null;
    /**
     *
     */
    deliveredAt: Date | null;
    /**
     *
     */
    deliveryAttempts: number;
    /**
     *
     */
    deliveryError: string | null;
    /**
     *
     */
    deliveryState: string;
    /**
     *
     */
    displayName: string;
    /**
     *
     */
    email: string;
    /**
     *
     */
    emailConfirmed: boolean;
    /**
     *
     */
    isAccountAdministrator: boolean;
    /**
     *
     */
    isEmployee: boolean;
    /**
     *
     */
    isManager: boolean;
    /**
     *
     */
    managerId: string | null;
    /**
     *
     */
    managerRelationshipValid: boolean;
    /**
     *
     */
    memberId: string;
    /**
     *
     */
    resendAvailableAt: Date | null;
    /**
     *
     */
    state: string;
    /**
     *
     */
    version: number;
}

/**
 * Check if a given object implements the InvitationProfile interface.
 */
export function instanceOfInvitationProfile(value: object): value is InvitationProfile {
    if (!('acceptedAt' in value) || value['acceptedAt'] === undefined) return false;
    if (!('accessVersion' in value) || value['accessVersion'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('cancelledAt' in value) || value['cancelledAt'] === undefined) return false;
    if (!('codeExpiresAt' in value) || value['codeExpiresAt'] === undefined) return false;
    if (!('deliveredAt' in value) || value['deliveredAt'] === undefined) return false;
    if (!('deliveryAttempts' in value) || value['deliveryAttempts'] === undefined) return false;
    if (!('deliveryError' in value) || value['deliveryError'] === undefined) return false;
    if (!('deliveryState' in value) || value['deliveryState'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('emailConfirmed' in value) || value['emailConfirmed'] === undefined) return false;
    if (!('isAccountAdministrator' in value) || value['isAccountAdministrator'] === undefined) return false;
    if (!('isEmployee' in value) || value['isEmployee'] === undefined) return false;
    if (!('isManager' in value) || value['isManager'] === undefined) return false;
    if (!('managerId' in value) || value['managerId'] === undefined) return false;
    if (!('managerRelationshipValid' in value) || value['managerRelationshipValid'] === undefined) return false;
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('resendAvailableAt' in value) || value['resendAvailableAt'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function InvitationProfileFromJSON(json: any): InvitationProfile {
    return InvitationProfileFromJSONTyped(json, false);
}

export function InvitationProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationProfile {
    if (json == null) {
        return json;
    }
    return {

        'acceptedAt': (json['acceptedAt'] == null ? null : parseDateTime(json['acceptedAt'])),
        'accessVersion': json['accessVersion'],
        'active': json['active'],
        'cancelledAt': (json['cancelledAt'] == null ? null : parseDateTime(json['cancelledAt'])),
        'codeExpiresAt': (json['codeExpiresAt'] == null ? null : parseDateTime(json['codeExpiresAt'])),
        'deliveredAt': (json['deliveredAt'] == null ? null : parseDateTime(json['deliveredAt'])),
        'deliveryAttempts': json['deliveryAttempts'],
        'deliveryError': json['deliveryError'],
        'deliveryState': json['deliveryState'],
        'displayName': json['displayName'],
        'email': json['email'],
        'emailConfirmed': json['emailConfirmed'],
        'isAccountAdministrator': json['isAccountAdministrator'],
        'isEmployee': json['isEmployee'],
        'isManager': json['isManager'],
        'managerId': json['managerId'],
        'managerRelationshipValid': json['managerRelationshipValid'],
        'memberId': json['memberId'],
        'resendAvailableAt': (json['resendAvailableAt'] == null ? null : parseDateTime(json['resendAvailableAt'])),
        'state': json['state'],
        'version': json['version'],
    };
}

export function InvitationProfileToJSON(json: any): InvitationProfile {
    return InvitationProfileToJSONTyped(json, false);
}

export function InvitationProfileToJSONTyped(value?: InvitationProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'acceptedAt': value['acceptedAt'] == null ? value['acceptedAt'] : serializeDateTime(value['acceptedAt']),
        'accessVersion': value['accessVersion'],
        'active': value['active'],
        'cancelledAt': value['cancelledAt'] == null ? value['cancelledAt'] : serializeDateTime(value['cancelledAt']),
        'codeExpiresAt': value['codeExpiresAt'] == null ? value['codeExpiresAt'] : serializeDateTime(value['codeExpiresAt']),
        'deliveredAt': value['deliveredAt'] == null ? value['deliveredAt'] : serializeDateTime(value['deliveredAt']),
        'deliveryAttempts': value['deliveryAttempts'],
        'deliveryError': value['deliveryError'],
        'deliveryState': value['deliveryState'],
        'displayName': value['displayName'],
        'email': value['email'],
        'emailConfirmed': value['emailConfirmed'],
        'isAccountAdministrator': value['isAccountAdministrator'],
        'isEmployee': value['isEmployee'],
        'isManager': value['isManager'],
        'managerId': value['managerId'],
        'managerRelationshipValid': value['managerRelationshipValid'],
        'memberId': value['memberId'],
        'resendAvailableAt': value['resendAvailableAt'] == null ? value['resendAvailableAt'] : serializeDateTime(value['resendAvailableAt']),
        'state': value['state'],
        'version': value['version'],
    };
}
