/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface InvitationChangeRequest
 */
export interface InvitationChangeRequest {
    /**
     *
     */
    commandId: string;
    /**
     *
     */
    expectedVersion: number;
}

/**
 * Check if a given object implements the InvitationChangeRequest interface.
 */
export function instanceOfInvitationChangeRequest(value: object): value is InvitationChangeRequest {
    if (!('commandId' in value) || value['commandId'] === undefined) return false;
    if (!('expectedVersion' in value) || value['expectedVersion'] === undefined) return false;
    return true;
}

export function InvitationChangeRequestFromJSON(json: any): InvitationChangeRequest {
    return InvitationChangeRequestFromJSONTyped(json, false);
}

export function InvitationChangeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitationChangeRequest {
    if (json == null) {
        return json;
    }
    return {

        'commandId': json['commandId'],
        'expectedVersion': json['expectedVersion'],
    };
}

export function InvitationChangeRequestToJSON(json: any): InvitationChangeRequest {
    return InvitationChangeRequestToJSONTyped(json, false);
}

export function InvitationChangeRequestToJSONTyped(value?: InvitationChangeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'commandId': value['commandId'],
        'expectedVersion': value['expectedVersion'],
    };
}
