/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface NotificationReadInput
 */
export interface NotificationReadInput {
    /**
     *
     */
    read: boolean;
}

/**
 * Check if a given object implements the NotificationReadInput interface.
 */
export function instanceOfNotificationReadInput(value: object): value is NotificationReadInput {
    if (!('read' in value) || value['read'] === undefined) return false;
    return true;
}

export function NotificationReadInputFromJSON(json: any): NotificationReadInput {
    return NotificationReadInputFromJSONTyped(json, false);
}

export function NotificationReadInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationReadInput {
    if (json == null) {
        return json;
    }
    return {

        'read': json['read'],
    };
}

export function NotificationReadInputToJSON(json: any): NotificationReadInput {
    return NotificationReadInputToJSONTyped(json, false);
}

export function NotificationReadInputToJSONTyped(value?: NotificationReadInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'read': value['read'],
    };
}
