/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface NotificationOperations
 */
export interface NotificationOperations {
    /**
     *
     */
    outboxFailed: number;
    /**
     *
     */
    outboxPending: number;
    /**
     *
     */
    providerAccepted: number;
    /**
     *
     */
    pushFailed: number;
    /**
     *
     */
    pushPending: number;
    /**
     *
     */
    simulated: number;
}

/**
 * Check if a given object implements the NotificationOperations interface.
 */
export function instanceOfNotificationOperations(value: object): value is NotificationOperations {
    if (!('outboxFailed' in value) || value['outboxFailed'] === undefined) return false;
    if (!('outboxPending' in value) || value['outboxPending'] === undefined) return false;
    if (!('providerAccepted' in value) || value['providerAccepted'] === undefined) return false;
    if (!('pushFailed' in value) || value['pushFailed'] === undefined) return false;
    if (!('pushPending' in value) || value['pushPending'] === undefined) return false;
    if (!('simulated' in value) || value['simulated'] === undefined) return false;
    return true;
}

export function NotificationOperationsFromJSON(json: any): NotificationOperations {
    return NotificationOperationsFromJSONTyped(json, false);
}

export function NotificationOperationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationOperations {
    if (json == null) {
        return json;
    }
    return {

        'outboxFailed': json['outboxFailed'],
        'outboxPending': json['outboxPending'],
        'providerAccepted': json['providerAccepted'],
        'pushFailed': json['pushFailed'],
        'pushPending': json['pushPending'],
        'simulated': json['simulated'],
    };
}

export function NotificationOperationsToJSON(json: any): NotificationOperations {
    return NotificationOperationsToJSONTyped(json, false);
}

export function NotificationOperationsToJSONTyped(value?: NotificationOperations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'outboxFailed': value['outboxFailed'],
        'outboxPending': value['outboxPending'],
        'providerAccepted': value['providerAccepted'],
        'pushFailed': value['pushFailed'],
        'pushPending': value['pushPending'],
        'simulated': value['simulated'],
    };
}
