/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const NotificationContext = {
    Request: 'Request',
    Proposal: 'Proposal',
    Requirement: 'Requirement',
    Task: 'Task',
} as const;
export type NotificationContext = typeof NotificationContext[keyof typeof NotificationContext];


export function instanceOfNotificationContext(value: any): boolean {
    for (const key in NotificationContext) {
        if (Object.prototype.hasOwnProperty.call(NotificationContext, key)) {
            if (NotificationContext[key as keyof typeof NotificationContext] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NotificationContextFromJSON(json: any): NotificationContext {
    return NotificationContextFromJSONTyped(json, false);
}

export function NotificationContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationContext {
    return json as NotificationContext;
}

export function NotificationContextToJSON(value?: NotificationContext | null): any {
    return value as any;
}

export function NotificationContextToJSONTyped(value: any, ignoreDiscriminator: boolean): NotificationContext {
    return value as NotificationContext;
}
