/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const OnsiteState = {
    Active: 'Active',
    NeedsResolution: 'NeedsResolution',
    Cancelled: 'Cancelled',
} as const;
export type OnsiteState = typeof OnsiteState[keyof typeof OnsiteState];


export function instanceOfOnsiteState(value: any): boolean {
    for (const key in OnsiteState) {
        if (Object.prototype.hasOwnProperty.call(OnsiteState, key)) {
            if (OnsiteState[key as keyof typeof OnsiteState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OnsiteStateFromJSON(json: any): OnsiteState {
    return OnsiteStateFromJSONTyped(json, false);
}

export function OnsiteStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnsiteState {
    return json as OnsiteState;
}

export function OnsiteStateToJSON(value?: OnsiteState | null): any {
    return value as any;
}

export function OnsiteStateToJSONTyped(value: any, ignoreDiscriminator: boolean): OnsiteState {
    return value as OnsiteState;
}
