/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface OnsiteConflict
 */
export interface OnsiteConflict {
    /**
     *
     */
    code: string;
    /**
     *
     */
    contextId: string;
    /**
     *
     */
    localDate: Date;
    /**
     *
     */
    requestId: string | null;
}

/**
 * Check if a given object implements the OnsiteConflict interface.
 */
export function instanceOfOnsiteConflict(value: object): value is OnsiteConflict {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('contextId' in value) || value['contextId'] === undefined) return false;
    if (!('localDate' in value) || value['localDate'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function OnsiteConflictFromJSON(json: any): OnsiteConflict {
    return OnsiteConflictFromJSONTyped(json, false);
}

export function OnsiteConflictFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnsiteConflict {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'],
        'contextId': json['contextId'],
        'localDate': (json['localDate'] == null ? json['localDate'] : parseDate(json['localDate'])),
        'requestId': json['requestId'],
    };
}

export function OnsiteConflictToJSON(json: any): OnsiteConflict {
    return OnsiteConflictToJSONTyped(json, false);
}

export function OnsiteConflictToJSONTyped(value?: OnsiteConflict | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'contextId': value['contextId'],
        'localDate': value['localDate'] == null ? value['localDate'] : serializeDate(value['localDate']),
        'requestId': value['requestId'],
    };
}
