/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OnsiteState } from './OnsiteState';
import {
    OnsiteStateFromJSON,
    OnsiteStateFromJSONTyped,
    OnsiteStateToJSON,
    OnsiteStateToJSONTyped,
} from './OnsiteState';
import type { OnsiteConflict } from './OnsiteConflict';
import {
    OnsiteConflictFromJSON,
    OnsiteConflictFromJSONTyped,
    OnsiteConflictToJSON,
    OnsiteConflictToJSONTyped,
} from './OnsiteConflict';

/**
 *
 * @export
 * @interface OnsitePreview
 */
export interface OnsitePreview {
    /**
     *
     */
    calendarVersion: number;
    /**
     *
     */
    conflicts: Array<OnsiteConflict>;
    /**
     *
     */
    result: OnsiteState;
}



/**
 * Check if a given object implements the OnsitePreview interface.
 */
export function instanceOfOnsitePreview(value: object): value is OnsitePreview {
    if (!('calendarVersion' in value) || value['calendarVersion'] === undefined) return false;
    if (!('conflicts' in value) || value['conflicts'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function OnsitePreviewFromJSON(json: any): OnsitePreview {
    return OnsitePreviewFromJSONTyped(json, false);
}

export function OnsitePreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnsitePreview {
    if (json == null) {
        return json;
    }
    return {

        'calendarVersion': json['calendarVersion'],
        'conflicts': ((json['conflicts'] as Array<any>).map(OnsiteConflictFromJSON)),
        'result': OnsiteStateFromJSON(json['result']),
    };
}

export function OnsitePreviewToJSON(json: any): OnsitePreview {
    return OnsitePreviewToJSONTyped(json, false);
}

export function OnsitePreviewToJSONTyped(value?: OnsitePreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'calendarVersion': value['calendarVersion'],
        'conflicts': ((value['conflicts'] as Array<any>).map(OnsiteConflictToJSON)),
        'result': OnsiteStateToJSON(value['result']),
    };
}
