/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OnsiteAcknowledgeInput
 */
export interface OnsiteAcknowledgeInput {
    /**
     *
     */
    expectedCalendarVersion: number | null;
    /**
     *
     */
    expectedVersion: number | null;
    /**
     *
     */
    revision: number;
}

/**
 * Check if a given object implements the OnsiteAcknowledgeInput interface.
 */
export function instanceOfOnsiteAcknowledgeInput(value: object): value is OnsiteAcknowledgeInput {
    if (!('expectedCalendarVersion' in value) || value['expectedCalendarVersion'] === undefined) return false;
    if (!('expectedVersion' in value) || value['expectedVersion'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    return true;
}

export function OnsiteAcknowledgeInputFromJSON(json: any): OnsiteAcknowledgeInput {
    return OnsiteAcknowledgeInputFromJSONTyped(json, false);
}

export function OnsiteAcknowledgeInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnsiteAcknowledgeInput {
    if (json == null) {
        return json;
    }
    return {

        'expectedCalendarVersion': json['expectedCalendarVersion'],
        'expectedVersion': json['expectedVersion'],
        'revision': json['revision'],
    };
}

export function OnsiteAcknowledgeInputToJSON(json: any): OnsiteAcknowledgeInput {
    return OnsiteAcknowledgeInputToJSONTyped(json, false);
}

export function OnsiteAcknowledgeInputToJSONTyped(value?: OnsiteAcknowledgeInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'expectedCalendarVersion': value['expectedCalendarVersion'],
        'expectedVersion': value['expectedVersion'],
        'revision': value['revision'],
    };
}
