/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface OnsiteInput
 */
export interface OnsiteInput {
    /**
     *
     */
    expectedCalendarVersion: number | null;
    /**
     *
     */
    expectedVersion: number | null;
    /**
     *
     */
    from: Date;
    /**
     *
     */
    location: string;
    /**
     *
     */
    reason: string;
    /**
     *
     */
    reference: string;
    /**
     *
     */
    to: Date;
}

/**
 * Check if a given object implements the OnsiteInput interface.
 */
export function instanceOfOnsiteInput(value: object): value is OnsiteInput {
    if (!('expectedCalendarVersion' in value) || value['expectedCalendarVersion'] === undefined) return false;
    if (!('expectedVersion' in value) || value['expectedVersion'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('reference' in value) || value['reference'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function OnsiteInputFromJSON(json: any): OnsiteInput {
    return OnsiteInputFromJSONTyped(json, false);
}

export function OnsiteInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnsiteInput {
    if (json == null) {
        return json;
    }
    return {

        'expectedCalendarVersion': json['expectedCalendarVersion'],
        'expectedVersion': json['expectedVersion'],
        'from': (json['from'] == null ? json['from'] : parseDate(json['from'])),
        'location': json['location'],
        'reason': json['reason'],
        'reference': json['reference'],
        'to': (json['to'] == null ? json['to'] : parseDate(json['to'])),
    };
}

export function OnsiteInputToJSON(json: any): OnsiteInput {
    return OnsiteInputToJSONTyped(json, false);
}

export function OnsiteInputToJSONTyped(value?: OnsiteInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'expectedCalendarVersion': value['expectedCalendarVersion'],
        'expectedVersion': value['expectedVersion'],
        'from': value['from'] == null ? value['from'] : serializeDate(value['from']),
        'location': value['location'],
        'reason': value['reason'],
        'reference': value['reference'],
        'to': value['to'] == null ? value['to'] : serializeDate(value['to']),
    };
}
