/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OnsiteView } from './OnsiteView';
import {
    OnsiteViewFromJSON,
    OnsiteViewFromJSONTyped,
    OnsiteViewToJSON,
    OnsiteViewToJSONTyped,
} from './OnsiteView';

/**
 *
 * @export
 * @interface OnsitePage
 */
export interface OnsitePage {
    /**
     *
     */
    calendarVersion: number;
    /**
     *
     */
    items: Array<OnsiteView>;
    /**
     *
     */
    nextOffset: number | null;
}

/**
 * Check if a given object implements the OnsitePage interface.
 */
export function instanceOfOnsitePage(value: object): value is OnsitePage {
    if (!('calendarVersion' in value) || value['calendarVersion'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextOffset' in value) || value['nextOffset'] === undefined) return false;
    return true;
}

export function OnsitePageFromJSON(json: any): OnsitePage {
    return OnsitePageFromJSONTyped(json, false);
}

export function OnsitePageFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnsitePage {
    if (json == null) {
        return json;
    }
    return {

        'calendarVersion': json['calendarVersion'],
        'items': ((json['items'] as Array<any>).map(OnsiteViewFromJSON)),
        'nextOffset': json['nextOffset'],
    };
}

export function OnsitePageToJSON(json: any): OnsitePage {
    return OnsitePageToJSONTyped(json, false);
}

export function OnsitePageToJSONTyped(value?: OnsitePage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'calendarVersion': value['calendarVersion'],
        'items': ((value['items'] as Array<any>).map(OnsiteViewToJSON)),
        'nextOffset': value['nextOffset'],
    };
}
