/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { WorkLocation } from './WorkLocation';
import {
    WorkLocationFromJSON,
    WorkLocationFromJSONTyped,
    WorkLocationToJSON,
    WorkLocationToJSONTyped,
} from './WorkLocation';

/**
 *
 * @export
 * @interface PatternView
 */
export interface PatternView {
    /**
     *
     */
    effectiveFrom: Date;
    /**
     *
     */
    locations: Array<WorkLocation>;
    /**
     *
     */
    version: number;
}

/**
 * Check if a given object implements the PatternView interface.
 */
export function instanceOfPatternView(value: object): value is PatternView {
    if (!('effectiveFrom' in value) || value['effectiveFrom'] === undefined) return false;
    if (!('locations' in value) || value['locations'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function PatternViewFromJSON(json: any): PatternView {
    return PatternViewFromJSONTyped(json, false);
}

export function PatternViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatternView {
    if (json == null) {
        return json;
    }
    return {

        'effectiveFrom': (json['effectiveFrom'] == null ? json['effectiveFrom'] : parseDate(json['effectiveFrom'])),
        'locations': ((json['locations'] as Array<any>).map(WorkLocationFromJSON)),
        'version': json['version'],
    };
}

export function PatternViewToJSON(json: any): PatternView {
    return PatternViewToJSONTyped(json, false);
}

export function PatternViewToJSONTyped(value?: PatternView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'effectiveFrom': value['effectiveFrom'] == null ? value['effectiveFrom'] : serializeDate(value['effectiveFrom']),
        'locations': ((value['locations'] as Array<any>).map(WorkLocationToJSON)),
        'version': value['version'],
    };
}
