/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { WorkLocation } from './WorkLocation';
import {
    WorkLocationFromJSON,
    WorkLocationFromJSONTyped,
    WorkLocationToJSON,
    WorkLocationToJSONTyped,
} from './WorkLocation';

/**
 *
 * @export
 * @interface PatternInput
 */
export interface PatternInput {
    /**
     *
     */
    effectiveFrom: Date;
    /**
     *
     */
    expectedCalendarVersion: number | null;
    /**
     *
     */
    locations: Array<WorkLocation>;
}

/**
 * Check if a given object implements the PatternInput interface.
 */
export function instanceOfPatternInput(value: object): value is PatternInput {
    if (!('effectiveFrom' in value) || value['effectiveFrom'] === undefined) return false;
    if (!('expectedCalendarVersion' in value) || value['expectedCalendarVersion'] === undefined) return false;
    if (!('locations' in value) || value['locations'] === undefined) return false;
    return true;
}

export function PatternInputFromJSON(json: any): PatternInput {
    return PatternInputFromJSONTyped(json, false);
}

export function PatternInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatternInput {
    if (json == null) {
        return json;
    }
    return {

        'effectiveFrom': (json['effectiveFrom'] == null ? json['effectiveFrom'] : parseDate(json['effectiveFrom'])),
        'expectedCalendarVersion': json['expectedCalendarVersion'],
        'locations': ((json['locations'] as Array<any>).map(WorkLocationFromJSON)),
    };
}

export function PatternInputToJSON(json: any): PatternInput {
    return PatternInputToJSONTyped(json, false);
}

export function PatternInputToJSONTyped(value?: PatternInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'effectiveFrom': value['effectiveFrom'] == null ? value['effectiveFrom'] : serializeDate(value['effectiveFrom']),
        'expectedCalendarVersion': value['expectedCalendarVersion'],
        'locations': ((value['locations'] as Array<any>).map(WorkLocationToJSON)),
    };
}
