/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PatternView } from './PatternView';
import {
    PatternViewFromJSON,
    PatternViewFromJSONTyped,
    PatternViewToJSON,
    PatternViewToJSONTyped,
} from './PatternView';

/**
 *
 * @export
 * @interface PatternPage
 */
export interface PatternPage {
    /**
     *
     */
    calendarVersion: number;
    /**
     *
     */
    items: Array<PatternView>;
    /**
     *
     */
    nextOffset: number | null;
}

/**
 * Check if a given object implements the PatternPage interface.
 */
export function instanceOfPatternPage(value: object): value is PatternPage {
    if (!('calendarVersion' in value) || value['calendarVersion'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextOffset' in value) || value['nextOffset'] === undefined) return false;
    return true;
}

export function PatternPageFromJSON(json: any): PatternPage {
    return PatternPageFromJSONTyped(json, false);
}

export function PatternPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatternPage {
    if (json == null) {
        return json;
    }
    return {

        'calendarVersion': json['calendarVersion'],
        'items': ((json['items'] as Array<any>).map(PatternViewFromJSON)),
        'nextOffset': json['nextOffset'],
    };
}

export function PatternPageToJSON(json: any): PatternPage {
    return PatternPageToJSONTyped(json, false);
}

export function PatternPageToJSONTyped(value?: PatternPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'calendarVersion': value['calendarVersion'],
        'items': ((value['items'] as Array<any>).map(PatternViewToJSON)),
        'nextOffset': value['nextOffset'],
    };
}
