/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequestedDayView } from './RequestedDayView';
import {
    RequestedDayViewFromJSON,
    RequestedDayViewFromJSONTyped,
    RequestedDayViewToJSON,
    RequestedDayViewToJSONTyped,
} from './RequestedDayView';

/**
 *
 * @export
 * @interface PendingDay
 */
export interface PendingDay {
    /**
     *
     */
    day: RequestedDayView;
    /**
     *
     */
    requestId: string;
    /**
     *
     */
    requestVersion: number;
}

/**
 * Check if a given object implements the PendingDay interface.
 */
export function instanceOfPendingDay(value: object): value is PendingDay {
    if (!('day' in value) || value['day'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('requestVersion' in value) || value['requestVersion'] === undefined) return false;
    return true;
}

export function PendingDayFromJSON(json: any): PendingDay {
    return PendingDayFromJSONTyped(json, false);
}

export function PendingDayFromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingDay {
    if (json == null) {
        return json;
    }
    return {

        'day': RequestedDayViewFromJSON(json['day']),
        'requestId': json['requestId'],
        'requestVersion': json['requestVersion'],
    };
}

export function PendingDayToJSON(json: any): PendingDay {
    return PendingDayToJSONTyped(json, false);
}

export function PendingDayToJSONTyped(value?: PendingDay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'day': RequestedDayViewToJSON(value['day']),
        'requestId': value['requestId'],
        'requestVersion': value['requestVersion'],
    };
}
