/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface PreviewDay
 */
export interface PreviewDay {
    /**
     *
     */
    isWeekend: boolean;
    /**
     *
     */
    localDate: Date;
}

/**
 * Check if a given object implements the PreviewDay interface.
 */
export function instanceOfPreviewDay(value: object): value is PreviewDay {
    if (!('isWeekend' in value) || value['isWeekend'] === undefined) return false;
    if (!('localDate' in value) || value['localDate'] === undefined) return false;
    return true;
}

export function PreviewDayFromJSON(json: any): PreviewDay {
    return PreviewDayFromJSONTyped(json, false);
}

export function PreviewDayFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreviewDay {
    if (json == null) {
        return json;
    }
    return {

        'isWeekend': json['isWeekend'],
        'localDate': (json['localDate'] == null ? json['localDate'] : parseDate(json['localDate'])),
    };
}

export function PreviewDayToJSON(json: any): PreviewDay {
    return PreviewDayToJSONTyped(json, false);
}

export function PreviewDayToJSONTyped(value?: PreviewDay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'isWeekend': value['isWeekend'],
        'localDate': value['localDate'] == null ? value['localDate'] : serializeDate(value['localDate']),
    };
}
