/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const ProposalState = {
    Open: 'Open',
    Accepted: 'Accepted',
    Superseded: 'Superseded',
} as const;
export type ProposalState = typeof ProposalState[keyof typeof ProposalState];


export function instanceOfProposalState(value: any): boolean {
    for (const key in ProposalState) {
        if (Object.prototype.hasOwnProperty.call(ProposalState, key)) {
            if (ProposalState[key as keyof typeof ProposalState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProposalStateFromJSON(json: any): ProposalState {
    return ProposalStateFromJSONTyped(json, false);
}

export function ProposalStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProposalState {
    return json as ProposalState;
}

export function ProposalStateToJSON(value?: ProposalState | null): any {
    return value as any;
}

export function ProposalStateToJSONTyped(value: any, ignoreDiscriminator: boolean): ProposalState {
    return value as ProposalState;
}
