/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DayInput } from './DayInput';
import {
    DayInputFromJSON,
    DayInputFromJSONTyped,
    DayInputToJSON,
    DayInputToJSONTyped,
} from './DayInput';
import type { SelectedDay } from './SelectedDay';
import {
    SelectedDayFromJSON,
    SelectedDayFromJSONTyped,
    SelectedDayToJSON,
    SelectedDayToJSONTyped,
} from './SelectedDay';

/**
 *
 * @export
 * @interface ProposalInput
 */
export interface ProposalInput {
    /**
     *
     */
    affectedDays: Array<SelectedDay>;
    /**
     *
     */
    days: Array<DayInput>;
    /**
     *
     */
    expectedCalendarVersion: number | null;
    /**
     *
     */
    expectedRequestVersion: number | null;
    /**
     *
     */
    reason: string;
    /**
     *
     */
    requirementId?: string | null;
    /**
     *
     */
    requirementRevision?: number | null;
}

/**
 * Check if a given object implements the ProposalInput interface.
 */
export function instanceOfProposalInput(value: object): value is ProposalInput {
    if (!('affectedDays' in value) || value['affectedDays'] === undefined) return false;
    if (!('days' in value) || value['days'] === undefined) return false;
    if (!('expectedCalendarVersion' in value) || value['expectedCalendarVersion'] === undefined) return false;
    if (!('expectedRequestVersion' in value) || value['expectedRequestVersion'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function ProposalInputFromJSON(json: any): ProposalInput {
    return ProposalInputFromJSONTyped(json, false);
}

export function ProposalInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProposalInput {
    if (json == null) {
        return json;
    }
    return {

        'affectedDays': ((json['affectedDays'] as Array<any>).map(SelectedDayFromJSON)),
        'days': ((json['days'] as Array<any>).map(DayInputFromJSON)),
        'expectedCalendarVersion': json['expectedCalendarVersion'],
        'expectedRequestVersion': json['expectedRequestVersion'],
        'reason': json['reason'],
        'requirementId': json['requirementId'] === undefined ? undefined : json['requirementId'] === null ? null : json['requirementId'],
        'requirementRevision': json['requirementRevision'] === undefined ? undefined : json['requirementRevision'] === null ? null : json['requirementRevision'],
    };
}

export function ProposalInputToJSON(json: any): ProposalInput {
    return ProposalInputToJSONTyped(json, false);
}

export function ProposalInputToJSONTyped(value?: ProposalInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'affectedDays': ((value['affectedDays'] as Array<any>).map(SelectedDayToJSON)),
        'days': ((value['days'] as Array<any>).map(DayInputToJSON)),
        'expectedCalendarVersion': value['expectedCalendarVersion'],
        'expectedRequestVersion': value['expectedRequestVersion'],
        'reason': value['reason'],
        'requirementId': value['requirementId'],
        'requirementRevision': value['requirementRevision'],
    };
}
