/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const PushProvider = {
    Disabled: 'Disabled',
    Local: 'Local',
    Fcm: 'Fcm',
} as const;
export type PushProvider = typeof PushProvider[keyof typeof PushProvider];


export function instanceOfPushProvider(value: any): boolean {
    for (const key in PushProvider) {
        if (Object.prototype.hasOwnProperty.call(PushProvider, key)) {
            if (PushProvider[key as keyof typeof PushProvider] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PushProviderFromJSON(json: any): PushProvider {
    return PushProviderFromJSONTyped(json, false);
}

export function PushProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PushProvider {
    return json as PushProvider;
}

export function PushProviderToJSON(value?: PushProvider | null): any {
    return value as any;
}

export function PushProviderToJSONTyped(value: any, ignoreDiscriminator: boolean): PushProvider {
    return value as PushProvider;
}
