/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { RequestState } from './RequestState';
import {
    RequestStateFromJSON,
    RequestStateFromJSONTyped,
    RequestStateToJSON,
    RequestStateToJSONTyped,
} from './RequestState';
import type { RequestedDayView } from './RequestedDayView';
import {
    RequestedDayViewFromJSON,
    RequestedDayViewFromJSONTyped,
    RequestedDayViewToJSON,
    RequestedDayViewToJSONTyped,
} from './RequestedDayView';

/**
 *
 * @export
 * @interface RequestView
 */
export interface RequestView {
    /**
     *
     */
    acceptedProposalId: string | null;
    /**
     *
     */
    createdAt: Date;
    /**
     *
     */
    days: Array<RequestedDayView>;
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    id: string;
    /**
     *
     */
    note: string;
    /**
     *
     */
    parentRevisionId: string | null;
    /**
     *
     */
    revision: number;
    /**
     *
     */
    rootId: string;
    /**
     *
     */
    state: RequestState;
    /**
     *
     */
    submittedAt: Date | null;
    /**
     *
     */
    version: number;
}



/**
 * Check if a given object implements the RequestView interface.
 */
export function instanceOfRequestView(value: object): value is RequestView {
    if (!('acceptedProposalId' in value) || value['acceptedProposalId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('days' in value) || value['days'] === undefined) return false;
    if (!('employeeId' in value) || value['employeeId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('note' in value) || value['note'] === undefined) return false;
    if (!('parentRevisionId' in value) || value['parentRevisionId'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    if (!('rootId' in value) || value['rootId'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('submittedAt' in value) || value['submittedAt'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function RequestViewFromJSON(json: any): RequestView {
    return RequestViewFromJSONTyped(json, false);
}

export function RequestViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestView {
    if (json == null) {
        return json;
    }
    return {

        'acceptedProposalId': json['acceptedProposalId'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'days': ((json['days'] as Array<any>).map(RequestedDayViewFromJSON)),
        'employeeId': json['employeeId'],
        'id': json['id'],
        'note': json['note'],
        'parentRevisionId': json['parentRevisionId'],
        'revision': json['revision'],
        'rootId': json['rootId'],
        'state': RequestStateFromJSON(json['state']),
        'submittedAt': (json['submittedAt'] == null ? null : parseDateTime(json['submittedAt'])),
        'version': json['version'],
    };
}

export function RequestViewToJSON(json: any): RequestView {
    return RequestViewToJSONTyped(json, false);
}

export function RequestViewToJSONTyped(value?: RequestView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'acceptedProposalId': value['acceptedProposalId'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'days': ((value['days'] as Array<any>).map(RequestedDayViewToJSON)),
        'employeeId': value['employeeId'],
        'id': value['id'],
        'note': value['note'],
        'parentRevisionId': value['parentRevisionId'],
        'revision': value['revision'],
        'rootId': value['rootId'],
        'state': RequestStateToJSON(value['state']),
        'submittedAt': value['submittedAt'] == null ? value['submittedAt'] : serializeDateTime(value['submittedAt']),
        'version': value['version'],
    };
}
