/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequestView } from './RequestView';
import {
    RequestViewFromJSON,
    RequestViewFromJSONTyped,
    RequestViewToJSON,
    RequestViewToJSONTyped,
} from './RequestView';

/**
 *
 * @export
 * @interface RequestPage
 */
export interface RequestPage {
    /**
     *
     */
    calendarVersion: number;
    /**
     *
     */
    items: Array<RequestView>;
    /**
     *
     */
    nextOffset: number | null;
}

/**
 * Check if a given object implements the RequestPage interface.
 */
export function instanceOfRequestPage(value: object): value is RequestPage {
    if (!('calendarVersion' in value) || value['calendarVersion'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextOffset' in value) || value['nextOffset'] === undefined) return false;
    return true;
}

export function RequestPageFromJSON(json: any): RequestPage {
    return RequestPageFromJSONTyped(json, false);
}

export function RequestPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestPage {
    if (json == null) {
        return json;
    }
    return {

        'calendarVersion': json['calendarVersion'],
        'items': ((json['items'] as Array<any>).map(RequestViewFromJSON)),
        'nextOffset': json['nextOffset'],
    };
}

export function RequestPageToJSON(json: any): RequestPage {
    return RequestPageToJSONTyped(json, false);
}

export function RequestPageToJSONTyped(value?: RequestPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'calendarVersion': value['calendarVersion'],
        'items': ((value['items'] as Array<any>).map(RequestViewToJSON)),
        'nextOffset': value['nextOffset'],
    };
}
