/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RetryNotificationInput
 */
export interface RetryNotificationInput {
    /**
     *
     */
    id: string;
    /**
     *
     */
    push: boolean;
}

/**
 * Check if a given object implements the RetryNotificationInput interface.
 */
export function instanceOfRetryNotificationInput(value: object): value is RetryNotificationInput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('push' in value) || value['push'] === undefined) return false;
    return true;
}

export function RetryNotificationInputFromJSON(json: any): RetryNotificationInput {
    return RetryNotificationInputFromJSONTyped(json, false);
}

export function RetryNotificationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetryNotificationInput {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'push': json['push'],
    };
}

export function RetryNotificationInputToJSON(json: any): RetryNotificationInput {
    return RetryNotificationInputToJSONTyped(json, false);
}

export function RetryNotificationInputToJSONTyped(value?: RetryNotificationInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'push': value['push'],
    };
}
