/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SetManagerRequest
 */
export interface SetManagerRequest {
    /**
     *
     */
    commandId?: string | null;
    /**
     *
     */
    expectedAccessVersion?: number | null;
    /**
     *
     */
    managerId: string | null;
}

/**
 * Check if a given object implements the SetManagerRequest interface.
 */
export function instanceOfSetManagerRequest(value: object): value is SetManagerRequest {
    if (!('managerId' in value) || value['managerId'] === undefined) return false;
    return true;
}

export function SetManagerRequestFromJSON(json: any): SetManagerRequest {
    return SetManagerRequestFromJSONTyped(json, false);
}

export function SetManagerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetManagerRequest {
    if (json == null) {
        return json;
    }
    return {

        'commandId': json['commandId'] === undefined ? undefined : json['commandId'] === null ? null : json['commandId'],
        'expectedAccessVersion': json['expectedAccessVersion'] === undefined ? undefined : json['expectedAccessVersion'] === null ? null : json['expectedAccessVersion'],
        'managerId': json['managerId'],
    };
}

export function SetManagerRequestToJSON(json: any): SetManagerRequest {
    return SetManagerRequestToJSONTyped(json, false);
}

export function SetManagerRequestToJSONTyped(value?: SetManagerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'commandId': value['commandId'],
        'expectedAccessVersion': value['expectedAccessVersion'],
        'managerId': value['managerId'],
    };
}
