/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SubmitInput
 */
export interface SubmitInput {
    /**
     *
     */
    expectedCalendarVersion: number | null;
    /**
     *
     */
    expectedRequestVersion: number | null;
}

/**
 * Check if a given object implements the SubmitInput interface.
 */
export function instanceOfSubmitInput(value: object): value is SubmitInput {
    if (!('expectedCalendarVersion' in value) || value['expectedCalendarVersion'] === undefined) return false;
    if (!('expectedRequestVersion' in value) || value['expectedRequestVersion'] === undefined) return false;
    return true;
}

export function SubmitInputFromJSON(json: any): SubmitInput {
    return SubmitInputFromJSONTyped(json, false);
}

export function SubmitInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitInput {
    if (json == null) {
        return json;
    }
    return {

        'expectedCalendarVersion': json['expectedCalendarVersion'],
        'expectedRequestVersion': json['expectedRequestVersion'],
    };
}

export function SubmitInputToJSON(json: any): SubmitInput {
    return SubmitInputToJSONTyped(json, false);
}

export function SubmitInputToJSONTyped(value?: SubmitInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'expectedCalendarVersion': value['expectedCalendarVersion'],
        'expectedRequestVersion': value['expectedRequestVersion'],
    };
}
