/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssignedTaskState } from './AssignedTaskState';
import {
    AssignedTaskStateFromJSON,
    AssignedTaskStateFromJSONTyped,
    AssignedTaskStateToJSON,
    AssignedTaskStateToJSONTyped,
} from './AssignedTaskState';

/**
 *
 * @export
 * @interface TaskProgressInput
 */
export interface TaskProgressInput {
    /**
     *
     */
    expectedCalendarVersion: number | null;
    /**
     *
     */
    expectedVersion: number | null;
    /**
     *
     */
    note: string;
    /**
     *
     */
    state: AssignedTaskState;
}



/**
 * Check if a given object implements the TaskProgressInput interface.
 */
export function instanceOfTaskProgressInput(value: object): value is TaskProgressInput {
    if (!('expectedCalendarVersion' in value) || value['expectedCalendarVersion'] === undefined) return false;
    if (!('expectedVersion' in value) || value['expectedVersion'] === undefined) return false;
    if (!('note' in value) || value['note'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function TaskProgressInputFromJSON(json: any): TaskProgressInput {
    return TaskProgressInputFromJSONTyped(json, false);
}

export function TaskProgressInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskProgressInput {
    if (json == null) {
        return json;
    }
    return {

        'expectedCalendarVersion': json['expectedCalendarVersion'],
        'expectedVersion': json['expectedVersion'],
        'note': json['note'],
        'state': AssignedTaskStateFromJSON(json['state']),
    };
}

export function TaskProgressInputToJSON(json: any): TaskProgressInput {
    return TaskProgressInputToJSONTyped(json, false);
}

export function TaskProgressInputToJSONTyped(value?: TaskProgressInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'expectedCalendarVersion': value['expectedCalendarVersion'],
        'expectedVersion': value['expectedVersion'],
        'note': value['note'],
        'state': AssignedTaskStateToJSON(value['state']),
    };
}
