/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { AssignedTaskState } from './AssignedTaskState';
import {
    AssignedTaskStateFromJSON,
    AssignedTaskStateFromJSONTyped,
    AssignedTaskStateToJSON,
    AssignedTaskStateToJSONTyped,
} from './AssignedTaskState';

/**
 *
 * @export
 * @interface TaskInput
 */
export interface TaskInput {
    /**
     *
     */
    deadline: Date;
    /**
     *
     */
    description: string;
    /**
     *
     */
    expectedCalendarVersion: number | null;
    /**
     *
     */
    expectedVersion: number | null;
    /**
     *
     */
    requirementId: string | null;
    /**
     *
     */
    requiresOnsite: boolean;
    /**
     *
     */
    state: AssignedTaskState;
    /**
     *
     */
    title: string;
}



/**
 * Check if a given object implements the TaskInput interface.
 */
export function instanceOfTaskInput(value: object): value is TaskInput {
    if (!('deadline' in value) || value['deadline'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('expectedCalendarVersion' in value) || value['expectedCalendarVersion'] === undefined) return false;
    if (!('expectedVersion' in value) || value['expectedVersion'] === undefined) return false;
    if (!('requirementId' in value) || value['requirementId'] === undefined) return false;
    if (!('requiresOnsite' in value) || value['requiresOnsite'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function TaskInputFromJSON(json: any): TaskInput {
    return TaskInputFromJSONTyped(json, false);
}

export function TaskInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskInput {
    if (json == null) {
        return json;
    }
    return {

        'deadline': (json['deadline'] == null ? json['deadline'] : parseDate(json['deadline'])),
        'description': json['description'],
        'expectedCalendarVersion': json['expectedCalendarVersion'],
        'expectedVersion': json['expectedVersion'],
        'requirementId': json['requirementId'],
        'requiresOnsite': json['requiresOnsite'],
        'state': AssignedTaskStateFromJSON(json['state']),
        'title': json['title'],
    };
}

export function TaskInputToJSON(json: any): TaskInput {
    return TaskInputToJSONTyped(json, false);
}

export function TaskInputToJSONTyped(value?: TaskInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'deadline': value['deadline'] == null ? value['deadline'] : serializeDate(value['deadline']),
        'description': value['description'],
        'expectedCalendarVersion': value['expectedCalendarVersion'],
        'expectedVersion': value['expectedVersion'],
        'requirementId': value['requirementId'],
        'requiresOnsite': value['requiresOnsite'],
        'state': AssignedTaskStateToJSON(value['state']),
        'title': value['title'],
    };
}
