/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { OnsiteState } from './OnsiteState';
import {
    OnsiteStateFromJSON,
    OnsiteStateFromJSONTyped,
    OnsiteStateToJSON,
    OnsiteStateToJSONTyped,
} from './OnsiteState';
import type { AssignedTaskState } from './AssignedTaskState';
import {
    AssignedTaskStateFromJSON,
    AssignedTaskStateFromJSONTyped,
    AssignedTaskStateToJSON,
    AssignedTaskStateToJSONTyped,
} from './AssignedTaskState';

/**
 *
 * @export
 * @interface TaskView
 */
export interface TaskView {
    /**
     *
     */
    deadline: Date;
    /**
     *
     */
    description: string;
    /**
     *
     */
    employeeId: string;
    /**
     *
     */
    id: string;
    /**
     *
     */
    progressNote: string;
    /**
     *
     */
    requirementId: string | null;
    /**
     *
     */
    requirementRevision: number | null;
    /**
     *
     */
    requirementState: OnsiteState | null;
    /**
     *
     */
    requiresOnsite: boolean;
    /**
     *
     */
    state: AssignedTaskState;
    /**
     *
     */
    title: string;
    /**
     *
     */
    version: number;
}



/**
 * Check if a given object implements the TaskView interface.
 */
export function instanceOfTaskView(value: object): value is TaskView {
    if (!('deadline' in value) || value['deadline'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('employeeId' in value) || value['employeeId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('progressNote' in value) || value['progressNote'] === undefined) return false;
    if (!('requirementId' in value) || value['requirementId'] === undefined) return false;
    if (!('requirementRevision' in value) || value['requirementRevision'] === undefined) return false;
    if (!('requirementState' in value) || value['requirementState'] === undefined) return false;
    if (!('requiresOnsite' in value) || value['requiresOnsite'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function TaskViewFromJSON(json: any): TaskView {
    return TaskViewFromJSONTyped(json, false);
}

export function TaskViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskView {
    if (json == null) {
        return json;
    }
    return {

        'deadline': (json['deadline'] == null ? json['deadline'] : parseDate(json['deadline'])),
        'description': json['description'],
        'employeeId': json['employeeId'],
        'id': json['id'],
        'progressNote': json['progressNote'],
        'requirementId': json['requirementId'],
        'requirementRevision': json['requirementRevision'],
        'requirementState': OnsiteStateFromJSON(json['requirementState']),
        'requiresOnsite': json['requiresOnsite'],
        'state': AssignedTaskStateFromJSON(json['state']),
        'title': json['title'],
        'version': json['version'],
    };
}

export function TaskViewToJSON(json: any): TaskView {
    return TaskViewToJSONTyped(json, false);
}

export function TaskViewToJSONTyped(value?: TaskView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'deadline': value['deadline'] == null ? value['deadline'] : serializeDate(value['deadline']),
        'description': value['description'],
        'employeeId': value['employeeId'],
        'id': value['id'],
        'progressNote': value['progressNote'],
        'requirementId': value['requirementId'],
        'requirementRevision': value['requirementRevision'],
        'requirementState': OnsiteStateToJSON(value['requirementState']),
        'requiresOnsite': value['requiresOnsite'],
        'state': AssignedTaskStateToJSON(value['state']),
        'title': value['title'],
        'version': value['version'],
    };
}
