/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateMemberRequest
 */
export interface UpdateMemberRequest {
    /**
     *
     */
    active: boolean;
    /**
     *
     */
    commandId?: string | null;
    /**
     *
     */
    expectedAccessVersion?: number | null;
    /**
     *
     */
    isAccountAdministrator: boolean;
    /**
     *
     */
    isEmployee: boolean;
    /**
     *
     */
    isManager: boolean;
}

/**
 * Check if a given object implements the UpdateMemberRequest interface.
 */
export function instanceOfUpdateMemberRequest(value: object): value is UpdateMemberRequest {
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('isAccountAdministrator' in value) || value['isAccountAdministrator'] === undefined) return false;
    if (!('isEmployee' in value) || value['isEmployee'] === undefined) return false;
    if (!('isManager' in value) || value['isManager'] === undefined) return false;
    return true;
}

export function UpdateMemberRequestFromJSON(json: any): UpdateMemberRequest {
    return UpdateMemberRequestFromJSONTyped(json, false);
}

export function UpdateMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMemberRequest {
    if (json == null) {
        return json;
    }
    return {

        'active': json['active'],
        'commandId': json['commandId'] === undefined ? undefined : json['commandId'] === null ? null : json['commandId'],
        'expectedAccessVersion': json['expectedAccessVersion'] === undefined ? undefined : json['expectedAccessVersion'] === null ? null : json['expectedAccessVersion'],
        'isAccountAdministrator': json['isAccountAdministrator'],
        'isEmployee': json['isEmployee'],
        'isManager': json['isManager'],
    };
}

export function UpdateMemberRequestToJSON(json: any): UpdateMemberRequest {
    return UpdateMemberRequestToJSONTyped(json, false);
}

export function UpdateMemberRequestToJSONTyped(value?: UpdateMemberRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'active': value['active'],
        'commandId': value['commandId'],
        'expectedAccessVersion': value['expectedAccessVersion'],
        'isAccountAdministrator': value['isAccountAdministrator'],
        'isEmployee': value['isEmployee'],
        'isManager': value['isManager'],
    };
}
