/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SelectedDay } from './SelectedDay';
import {
    SelectedDayFromJSON,
    SelectedDayFromJSONTyped,
    SelectedDayToJSON,
    SelectedDayToJSONTyped,
} from './SelectedDay';

/**
 *
 * @export
 * @interface WithdrawInput
 */
export interface WithdrawInput {
    /**
     *
     */
    days: Array<SelectedDay>;
    /**
     *
     */
    expectedCalendarVersion: number | null;
    /**
     *
     */
    expectedRequestVersion: number | null;
}

/**
 * Check if a given object implements the WithdrawInput interface.
 */
export function instanceOfWithdrawInput(value: object): value is WithdrawInput {
    if (!('days' in value) || value['days'] === undefined) return false;
    if (!('expectedCalendarVersion' in value) || value['expectedCalendarVersion'] === undefined) return false;
    if (!('expectedRequestVersion' in value) || value['expectedRequestVersion'] === undefined) return false;
    return true;
}

export function WithdrawInputFromJSON(json: any): WithdrawInput {
    return WithdrawInputFromJSONTyped(json, false);
}

export function WithdrawInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithdrawInput {
    if (json == null) {
        return json;
    }
    return {

        'days': ((json['days'] as Array<any>).map(SelectedDayFromJSON)),
        'expectedCalendarVersion': json['expectedCalendarVersion'],
        'expectedRequestVersion': json['expectedRequestVersion'],
    };
}

export function WithdrawInputToJSON(json: any): WithdrawInput {
    return WithdrawInputToJSONTyped(json, false);
}

export function WithdrawInputToJSONTyped(value?: WithdrawInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'days': ((value['days'] as Array<any>).map(SelectedDayToJSON)),
        'expectedCalendarVersion': value['expectedCalendarVersion'],
        'expectedRequestVersion': value['expectedRequestVersion'],
    };
}
