/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface WorkCommentInput
 */
export interface WorkCommentInput {
    /**
     *
     */
    expectedCalendarVersion: number | null;
    /**
     *
     */
    text: string;
}

/**
 * Check if a given object implements the WorkCommentInput interface.
 */
export function instanceOfWorkCommentInput(value: object): value is WorkCommentInput {
    if (!('expectedCalendarVersion' in value) || value['expectedCalendarVersion'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function WorkCommentInputFromJSON(json: any): WorkCommentInput {
    return WorkCommentInputFromJSONTyped(json, false);
}

export function WorkCommentInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkCommentInput {
    if (json == null) {
        return json;
    }
    return {

        'expectedCalendarVersion': json['expectedCalendarVersion'],
        'text': json['text'],
    };
}

export function WorkCommentInputToJSON(json: any): WorkCommentInput {
    return WorkCommentInputToJSONTyped(json, false);
}

export function WorkCommentInputToJSONTyped(value?: WorkCommentInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'expectedCalendarVersion': value['expectedCalendarVersion'],
        'text': value['text'],
    };
}
