/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const WorkContext = {
    Requirement: 'Requirement',
    Task: 'Task',
} as const;
export type WorkContext = typeof WorkContext[keyof typeof WorkContext];


export function instanceOfWorkContext(value: any): boolean {
    for (const key in WorkContext) {
        if (Object.prototype.hasOwnProperty.call(WorkContext, key)) {
            if (WorkContext[key as keyof typeof WorkContext] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WorkContextFromJSON(json: any): WorkContext {
    return WorkContextFromJSONTyped(json, false);
}

export function WorkContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkContext {
    return json as WorkContext;
}

export function WorkContextToJSON(value?: WorkContext | null): any {
    return value as any;
}

export function WorkContextToJSONTyped(value: any, ignoreDiscriminator: boolean): WorkContext {
    return value as WorkContext;
}
