/* tslint:disable */
/* eslint-disable */
/**
 * HomeOfficeReservation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 *
 * @export
 * @interface WorkEntryView
 */
export interface WorkEntryView {
    /**
     *
     */
    action: string;
    /**
     *
     */
    authorId: string;
    /**
     *
     */
    calendarVersion: number;
    /**
     *
     */
    createdAt: Date;
    /**
     *
     */
    id: string;
    /**
     *
     */
    snapshotJson: string;
    /**
     *
     */
    text: string;
}

/**
 * Check if a given object implements the WorkEntryView interface.
 */
export function instanceOfWorkEntryView(value: object): value is WorkEntryView {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('calendarVersion' in value) || value['calendarVersion'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('snapshotJson' in value) || value['snapshotJson'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function WorkEntryViewFromJSON(json: any): WorkEntryView {
    return WorkEntryViewFromJSONTyped(json, false);
}

export function WorkEntryViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkEntryView {
    if (json == null) {
        return json;
    }
    return {

        'action': json['action'],
        'authorId': json['authorId'],
        'calendarVersion': json['calendarVersion'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'id': json['id'],
        'snapshotJson': json['snapshotJson'],
        'text': json['text'],
    };
}

export function WorkEntryViewToJSON(json: any): WorkEntryView {
    return WorkEntryViewToJSONTyped(json, false);
}

export function WorkEntryViewToJSONTyped(value?: WorkEntryView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'action': value['action'],
        'authorId': value['authorId'],
        'calendarVersion': value['calendarVersion'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'id': value['id'],
        'snapshotJson': value['snapshotJson'],
        'text': value['text'],
    };
}
