// Generated by scripts/generate_theme.py. Edit design/tokens.json.
import 'package:flutter/material.dart';

class ThemeTokens {
  const ThemeTokens(this.dark);
  final bool dark;
  Color get background =>
      dark ? const Color(0xff262624) : const Color(0xfffaf9f5);
  Color get foreground =>
      dark ? const Color(0xfff1f1ef) : const Color(0xff3d3929);
  Color get surface => dark ? const Color(0xff2c2c2b) : const Color(0xfff5f4ef);
  Color get surfaceForeground =>
      dark ? const Color(0xfffaf9f5) : const Color(0xff141413);
  Color get popover => dark ? const Color(0xff30302e) : const Color(0xffffffff);
  Color get muted => dark ? const Color(0xff1b1b19) : const Color(0xffede9de);
  Color get mutedForeground =>
      dark ? const Color(0xffb7b5a9) : const Color(0xff66645d);
  Color get primary => dark ? const Color(0xffe08a6d) : const Color(0xffa84e32);
  Color get primaryForeground =>
      dark ? const Color(0xff141413) : const Color(0xffffffff);
  Color get secondary =>
      dark ? const Color(0xff383833) : const Color(0xffe9e6dc);
  Color get secondaryForeground =>
      dark ? const Color(0xfff1f1ef) : const Color(0xff535146);
  Color get accent => dark ? const Color(0xff40312b) : const Color(0xfff1e3d9);
  Color get border => dark ? const Color(0xff3e3e38) : const Color(0xffdad9d4);
  Color get input => dark ? const Color(0xff8d897b) : const Color(0xff827d70);
  Color get ring => dark ? const Color(0xffd97757) : const Color(0xffa84e32);
  Color get pending => dark ? const Color(0xffedc57b) : const Color(0xff785109);
  Color get pendingSurface =>
      dark ? const Color(0xff3e3424) : const Color(0xfffbefd5);
  Color get danger => dark ? const Color(0xfff0b0a5) : const Color(0xff9e342d);
  Color get dangerSurface =>
      dark ? const Color(0xff462c2a) : const Color(0xfffae8e4);
  Color get info => dark ? const Color(0xffaec8e7) : const Color(0xff3c5c80);
  Color get infoSurface =>
      dark ? const Color(0xff29384c) : const Color(0xffe8eef5);
}
